xamarin/XamarinCommunityToolkit

nuget/Controls.nuspec, nuget/Effects.nuspec
Fixes #22 
Changes Proposed in this pull request:
- Changing Win10 monniker to uap10.0
=> Fixing NuGet monnikers

.editorconfig, Contributing.md
Changes Proposed in this pull request:
- Added editorconfig
- Fixed some punctuation
=> Editorconfig and Contributing.md

src/Effects/Effects.Android/Effects/Switch/SwitchChangeColor.cs
Toggled event and value is being eaten by the effect implementation!
Need to apply the value to the Xamarin forms Control
Fixes #31
=> Toggled event and value is being eaten by the effect implementation!

Samples/Samples/Samples/Samples.csproj, Samples/Samples/Samples/Views/EffectsEntryRemoveBorderPage.xaml.cs, Samples/Samples/Samples/Views/EffectsEntryRemoveLinePage.xaml.cs, Samples/Samples/Samples/Views/EffectsEntrySelectAllTextPage.xaml.cs, Samples/Samples/Samples/Views/EffectsLabelPage.xaml, Samples/Samples/Samples/Views/EffectsLabelPage.xaml.cs, Samples/Samples/Samples/Views/EffectsLabelSizeFontToFitPage.xaml, Samples/Samples/Samples/Views/EffectsLabelSizeFontToFitPage.xaml.cs, Samples/Samples/Samples/Views/EffectsPage.xaml, Samples/Samples/Samples/Views/EffectsPage.xaml.cs, bootstrapper.ps1, build.cake, cake.packages.config
=> Added Size Font To Fit label effect sample

README.md
Please take a moment to fill out the following:
Fixes AppVeyor badge as all solutions are in the same repo now.
=> Updating AppVeyor badge

docs/Converters/ValueConverterGroup.md, src/Converters/Converters.Tests/Converters.Tests.csproj, src/Converters/Converters.Tests/Mocks/MockConverter.cs, src/Converters/Converters.Tests/ValueConverterGroupTests.cs, src/Converters/Converters/Converters.csproj, src/Converters/Converters/ValueConverterGroup.cs
Multiple converters #56 
Migrated from my repository https://github.com/XForms/XForms.Converters
=> Multiple converters

README.md
Please take a moment to fill out the following:
Fixes # .
Changes Proposed in this pull request:
-
-
-
=> Make it easy to spot esp on mobile

Samples/Samples/Samples.Android/Resources/Resource.Designer.cs, Samples/Samples/Samples.Android/Samples.Android.csproj, Samples/Samples/Samples.Android/Samples.Android.csproj.bak, Samples/Samples/Samples/Views/AnimationsPage.xaml, nuget/Animations.nuspec, src/Animations.sln, src/Animations/Animations/Animations.csproj, src/Animations/Animations/Animations/ColorAnimation.cs, src/Animations/Animations/Extensions/ColorExtensions.cs
Added ColorAnimation to the Animations Library
Updated Animations Sample
Added Animations nuspec
=> Updated Animations library, updated sample and added Animations nuspec

README.md
Removed obsolete link to readthedocs
=> Remove readthedocs link

Toolkit/Animations/Animations/HeartAnimation.cs
=> Typo correction

Toolkit/Effects/Base/Effects.android.cs
Fix of another small typo from a copy/paste.
=> Fix another typo

README.md
Incorrect links.
Changes Proposed in this pull request:
- Link to Contributing.md 
- Link to CODE_OF_CONDUCT.md
=> README.md - Fixes links

Samples/Samples/Views/AnimationsPage.xaml.cs, Toolkit/Animations/Extensions/AnimationExtension.cs
Append `.Extensions` to the `AnimationExtension` file's namespace (it's in the Extensions folder and the other file uses the same namespace, so we can remain consistent).
=> Animations.Extensions namespace adjustment

Samples/Samples.Android/Samples.Android.csproj, Samples/Samples.UWP/Samples.UWP.csproj, Samples/Samples.iOS/Samples.iOS.csproj, Samples/Samples/Samples.csproj, Tests/Behaviors.Tests/Behaviors.Tests.csproj, Tests/Converters.Tests/Converters.Tests.csproj, Toolkit/Animations/Animations.csproj, Toolkit/Behaviors/Behaviors.csproj, Toolkit/Converters/Converters.csproj, Toolkit/Directory.build.targets, Toolkit/Effects/Effects.csproj, Toolkit/Effects/Switch/SwitchChangeColor.uwp.cs
Update packages to the now stable XF 3.0, and a minor tweak to code using the VisualStateManager in UWP.
=> Update to XF 3.0

Samples/Samples.Android/Properties/AndroidManifest.xml, Samples/Samples.Android/Resources/Resource.designer.cs, Samples/Samples.Android/Samples.Android.csproj, Samples/Samples.UWP/Samples.UWP.csproj, Samples/Samples.iOS/Samples.iOS.csproj, Samples/Samples/Samples.csproj, Tests/Behaviors.Tests/Behaviors.Tests.csproj, Tests/Converters.Tests/Converters.Tests.csproj, Toolkit/Animations/Animations.csproj, Toolkit/Behaviors/Behaviors.csproj, Toolkit/Converters/Converters.csproj, Toolkit/Directory.build.props, Toolkit/Directory.build.targets, Toolkit/Effects/Effects.csproj
=> Update NuGet pcakges and sync settings in

Contributing.md, SUBMITTING-ISSUES.md
GitHub links are case sensitive
=> Fix the link to contributing.md

XamarinCommunityToolkit/Views/AvatarView.shared.cs, XamarinCommunityToolkit/XamarinCommunityToolkit.csproj, XamarinCommunityToolkitSample.Android/Resources/Resource.designer.cs, XamarinCommunityToolkitSample.Android/XamarinCommunityToolkitSample.Android.csproj, XamarinCommunityToolkitSample.iOS/XamarinCommunityToolkitSample.iOS.csproj, XamarinCommunityToolkitSample/App.xaml.cs, XamarinCommunityToolkitSample/Models/Views/ViewSectionId.cs, XamarinCommunityToolkitSample/Models/Views/ViewSectionModel.cs, XamarinCommunityToolkitSample/Pages/BehaviorsPage.xaml, XamarinCommunityToolkitSample/Pages/BehaviorsPage.xaml.cs, XamarinCommunityToolkitSample/Pages/Views/AvatarViewPage.xaml, XamarinCommunityToolkitSample/Pages/Views/AvatarViewPage.xaml.cs, XamarinCommunityToolkitSample/Pages/Views/ViewsGalleryPage.xaml, XamarinCommunityToolkitSample/Pages/Views/ViewsGalleryPage.xaml.cs, XamarinCommunityToolkitSample/Pages/WelcomePage.xaml, XamarinCommunityToolkitSample/Pages/WelcomePage.xaml.cs, XamarinCommunityToolkitSample/ViewModels/Views/AvatarViewViewModel.cs, XamarinCommunityToolkitSample/ViewModels/Views/ViewsGalleryViewModel.cs, XamarinCommunityToolkitSample/XamarinCommunityToolkitSample.csproj
AvatarView is a control for representing profile picture or placeholder text in case the picture is absent.
API:
```csharp
class AvatarView {
public double Size { get; set; }
public double CornerRadius { get; set; }
public Color BorderColor { get; set; }
public Color Color { get; set; }
public ImageSource Source { get; set; }
public string Text { get; set; }
public Color TextColor { get; set; }
public string FontFamily { get; set; }
public double FontSize { get; set; }
public FontAttributes FontAttributes { get; set; }
}
```
- Related to issue #134 
Added: 
- `AvatarView`
**Test Sample**
```xaml
<?xml version="1.0" encoding="utf-8"?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" …
```
=> AvatarView

XamarinCommunityToolkit.UnitTests/Converters/BoolToObjectConverter_Tests.cs, XamarinCommunityToolkit.UnitTests/Converters/DoubleToIntConverter_Tests.cs, XamarinCommunityToolkit.UnitTests/Converters/EqualConverter_Tests.cs, XamarinCommunityToolkit.UnitTests/Converters/IndexToArrayItemConverter_Tests.cs, XamarinCommunityToolkit.UnitTests/Converters/IntToBoolConverter_Tests.cs, XamarinCommunityToolkit.UnitTests/Converters/InvertedBoolConverter_Tests.cs, XamarinCommunityToolkit.UnitTests/Converters/IsNotNullOrEmptyConverter_Tests.cs, XamarinCommunityToolkit.UnitTests/Converters/ListIsNotNullOrEmptyConverter_Tests.cs, XamarinCommunityToolkit.UnitTests/Converters/ListIsNullOrEmptyConverter_Tests.cs, XamarinCommunityToolkit.UnitTests/Converters/MultiConverterParameter_Tests.cs, XamarinCommunityToolkit.UnitTests/Converters/MultiConverter_Tests.cs, XamarinCommunityToolkit.UnitTests/Converters/NotEqualConverter_Tests.cs, XamarinCommunityToolkit.UnitTests/Converters/TextCaseConverter_Tests.cs, XamarinCommunityToolkit.UnitTests/XamarinCommunityToolkit.UnitTests.csproj, XamarinCommunityToolkit/XamarinCommunityToolkit.csproj, XamarinCommunityToolkitSample.sln
Created a xUnit Test project. 
Added: 
- BoolToObjectConverter_Tests
- DoubleToIntConverter_Tests
- EqualConverter_Tests
- IndexToArrayItemConverter_Tests
NOTE: I'll continue working with the rest of the tests in another PR.
=> Adding UnitTest project and some Converters tests

XamarinCommunityToolkit/Views/RangeSlider.shared.cs, XamarinCommunityToolkitSample/Pages/Views/RangeSliderPage.xaml, XamarinCommunityToolkitSample/Pages/Views/RangeSliderPage.xaml.cs, XamarinCommunityToolkitSample/ViewModels/Views/ViewsGalleryViewModel.cs
**RangeSlider** works as a Slider with two thumbs allowing select two values (Lower and Upper) which represent "Range".
Could be very useful for some apps.
**Video**:
https://twitter.com/Andrik_Just4Fun/status/1283181731584053249
**TODO:**
I'd like to enhance this control by adding new properties
- Orientation (Horizontal | Vertical)
- ValueLabelPosition (Start | End) ~ (Top | Bottom for Horizontal Orientation and Left | Right for Vertical one)
- Related to issue #6
Supported Properties
| Name                        | Default Value | Description |
| --------------------------- | ----------- | ----------- |
| LowerValue                  | 0.0         | Current lower value |
| UpperValue                  | 1.0         | Current upper value |
| MinimumValue                | 0.0         | …
=> RangeSlider

XamarinCommunityToolkitSample/Resx/AppResources.Designer.cs
During the namespace refactoring one small thing was missed (Resource path wasn't regenerated in the resource designer file). It causes crash on the sample's start
None
None
=> Fixed Sample crash

XamarinCommunityToolkitSample/Resx/AppResources.Designer.cs, XamarinCommunityToolkitSample/Resx/AppResources.resx
Added missing Resx strings for UriValidationDescription and UriValidationShortDescription.
No tests included as this is part of sample code.
#217 
None
Added: 
UriValidationDescription resource
UriValidationShortDescription resource
Changed:
None
None
=> Added missing strings in AppResources.resx for UriValidationBehavior

.gitignore
Added .mfractor to .gitignore
- Closes #228 
Nope
Nah
=> Added .mfractor to gitignore

XamarinCommunityToolkit.UnitTests/Namespace_Tests.cs, XamarinCommunityToolkit/Behaviors/BaseBehavior.shared.cs, XamarinCommunityToolkit/Behaviors/EventToCommandBehavior.shared.cs, XamarinCommunityToolkit/Behaviors/MaskedBehavior.shared.cs, XamarinCommunityToolkit/Behaviors/UserStoppedTypingBehavior.shared.cs, XamarinCommunityToolkit/Behaviors/Validators/ValidationBehavior.shared.cs
- Make BaseBehavior be a generic class
- Update namespace unit tests file name and small test fix
- Clean MaskeBehavior
- Clean UserStoppedTypingBehavior and fix ForceUnfocuc feature (Should be invoked in UI thread)
None
None
=> Make BaseBehavior generic

XamarinCommunityToolkit/Views/CameraView/Android/CameraFragment.android.cs
Fixed the rotation of saved photos
- Fixes #297
None.
None.
=> [Bug] [CameraView] [Android] Fixed rotation of saved photos

README.md
-Fixes #325
see https://github.com/xamarin/Xamarin.Forms/issues/12223
=> Fix Nuget Badge in readme

.github/ISSUE_TEMPLATE/feature-request.md, .github/PULL_REQUEST_TEMPLATE.md
Some improvements to the templates.
* Adds descriptive things in comments to make those invisible on the issue page whenever they don't remove it
* Added a little checkmark on the feature request so we know if the author wants to pick it up themselves
- Fixes #343
=> Updated GH templates

XamarinCommunityToolkit/Actions/Snackbar/Snackbar.shared.cs, XamarinCommunityToolkit/Extensions/PageExtension.shared.cs, XamarinCommunityToolkit/Views/Snackbar/ActionArguments.shared.cs, XamarinCommunityToolkit/Views/Snackbar/Helpers/SnackbarLayout.ios.macos.cs, XamarinCommunityToolkit/Views/Snackbar/Helpers/iOS/Extensions/UIViewExtensions.ios.cs, XamarinCommunityToolkit/Views/Snackbar/Helpers/iOS/IOSSnackBar.ios.cs, XamarinCommunityToolkit/Views/Snackbar/Helpers/iOS/SnackbarAppearance.ios.cs, XamarinCommunityToolkit/Views/Snackbar/Helpers/iOS/SnackbarViews/ActionMessageSnackbarView.ios.cs, XamarinCommunityToolkit/Views/Snackbar/Helpers/iOS/SnackbarViews/BaseSnackbarView.ios.cs, XamarinCommunityToolkit/Views/Snackbar/Helpers/iOS/SnackbarViews/MessageSnackbarView.ios.cs, XamarinCommunityToolkit/Views/Snackbar/Helpers/macOS/MacOSSnackBar.macos.cs, XamarinCommunityToolkit/Views/Snackbar/Helpers/macOS/SnackbarAppearance.macos.cs, XamarinCommunityToolkit/Views/Snackbar/Helpers/macOS/SnackbarViews/ActionMessageSnackbarView.macos.cs, XamarinCommunityToolkit/Views/Snackbar/Helpers/macOS/SnackbarViews/BaseSnackbarView.macos.cs, XamarinCommunityToolkit/Views/Snackbar/Helpers/macOS/SnackbarViews/MessageSnackbarView.macos.cs, XamarinCommunityToolkit/Views/Snackbar/Snackbar.android.cs, XamarinCommunityToolkit/Views/Snackbar/Snackbar.ios.macos.cs, XamarinCommunityToolkit/Views/Snackbar/Snackbar.tizen.cs, XamarinCommunityToolkit/Views/Snackbar/Snackbar.uwp.cs, XamarinCommunityToolkit/Views/Snackbar/Snackbar.wpf.cs, XamarinCommunityToolkit/Views/Snackbar/SnackbarArguments.shared.cs, XamarinCommunityToolkitSample/Pages/Views/ActionsPage.xaml
Changed Snackbar and all related things to the right namespace and folders etc. Also some minor styling in the sample page.
I have also made most of the APIs private/internal since we want people to go through the extension anyway?
- Fixes #344
=> Moved Snackbar to right namespace

XamarinCommunityToolkit/Views/MediaElement/Android/FormsVideoView.android.cs, XamarinCommunityToolkit/Views/MediaElement/Android/MediaElementRenderer.android.cs, XamarinCommunityToolkit/Views/MediaElement/FileMediaSourceConverter.shared.cs, XamarinCommunityToolkit/Views/MediaElement/MediaElement.shared.cs, XamarinCommunityToolkit/Views/MediaElement/MediaSource.shared.cs, XamarinCommunityToolkit/Views/MediaElement/MediaSourceConverter.shared.cs, XamarinCommunityToolkit/Views/MediaElement/UWP/AspectExtensions.uwp.cs, XamarinCommunityToolkit/Views/MediaElement/UWP/MediaElementRenderer.uwp.cs, XamarinCommunityToolkit/Views/MediaElement/UriMediaSource.shared.cs, XamarinCommunityToolkit/Views/MediaElement/UriTypeConverter.shared.cs, XamarinCommunityToolkit/Views/MediaElement/iOS/MediaElementRenderer.ios.cs
This PR is just to:
1. Adjust the code to match our code style;
2. Remove `sealed` from classes and add `protected` and `virtual` to some methods.
This PR is to get MediaElement ready to be merged into the `main` branch.
=> MediaElement code style

azure-pipelines.yml
Enables code coverage reporting on our unit test runs
=> Enable code coverage on tests

XamarinCommunityToolkit/Effects/VisualFeedback/VisualFeedbackEffectRouter.ios.cs, XamarinCommunityToolkit/Views/TabView/TabView.shared.cs, XamarinCommunityToolkitSample/Pages/Views/TabView/CustomTabsPage.xaml, XamarinCommunityToolkitSample/Pages/Views/TabView/GettingStartedPage.xaml
Changes:
- Fixed issue with wrong SelectedIndex update.
- Fixed Tab Content size using CornerRadius in the TabStrip.
- Improved VisualFeedback effect in iOS.
None
None
=> Tabview Fixes

README.md
Updated README.md with new XmlnsDefinition in AvatarView sample usage
- Fixes #538
=> Updated README.md with new XmlnsDefinition in AvatarView sample usage code

XamarinCommunityToolkitSample/Pages/Behaviors/BehaviorsGalleryPage.xaml, XamarinCommunityToolkitSample/Pages/Converters/ConvertersGalleryPage.xaml, XamarinCommunityToolkitSample/Pages/Effects/EffectsGalleryPage.xaml, XamarinCommunityToolkitSample/Pages/Effects/SafeAreaEffectPage.xaml, XamarinCommunityToolkitSample/Pages/Extensions/ExtensionsGalleryPage.xaml, XamarinCommunityToolkitSample/Pages/TestCases/TestCasesGalleryPage.xaml, XamarinCommunityToolkitSample/Pages/Views/SnackBarPage.xaml, XamarinCommunityToolkitSample/Pages/Views/TabView/CustomTabsPage.xaml, XamarinCommunityToolkitSample/Pages/Views/TabView/GettingStartedPage.xaml, XamarinCommunityToolkitSample/Pages/Views/TabView/IsTabStripVisiblePage.xaml, XamarinCommunityToolkitSample/Pages/Views/TabView/NestedTabsPage.xaml, XamarinCommunityToolkitSample/Pages/Views/TabView/NoContentPage.xaml, XamarinCommunityToolkitSample/Pages/Views/TabView/ScrollTabsPage.xaml, XamarinCommunityToolkitSample/Pages/Views/TabView/TabBadgePage.xaml, XamarinCommunityToolkitSample/Pages/Views/TabView/TabItemAnimationPage.xaml, XamarinCommunityToolkitSample/Pages/Views/TabView/TabItemsSourcePage.xaml, XamarinCommunityToolkitSample/Pages/Views/TabView/TabPlacementPage.xaml, XamarinCommunityToolkitSample/Pages/Views/TabView/TabViewPage.xaml, XamarinCommunityToolkitSample/Pages/Views/TabView/TabWidthPage.xaml, XamarinCommunityToolkitSample/Pages/Views/ViewsGalleryPage.xaml, XamarinCommunityToolkitSample/Pages/WelcomePage.xaml
Implemented usage of the new XmlnsDefinition for the XamarinCommunityToolkit on all TabView sample pages.
- Fixes task 1 of #529
=> Changed the TabView samples to use the XmlnsDefinition improvement

XamarinCommunityToolkit/Resources/Layout/CameraFragment.axml, XamarinCommunityToolkit/Views/CameraView/Android/AutoFitTextureView.android.cs, XamarinCommunityToolkit/Views/CameraView/Android/CameraFragment.android.cs, XamarinCommunityToolkitSample/Pages/Views/CameraViewPage.xaml
Now the CameraView fills better View space defined in XF.
- Fixes #300
A nice coffee + milk to test the fix!
=> Fixed CameraView size

Xamarin.CommunityToolkit.MarkupSample/SearchViewModel.cs
Actual Tweet was from January, not October. :)
https://twitter.com/davidortinau/status/1221123588125876225?s=21
=> correcting date

README.md
=> Fixes sample link

azure-pipelines.yml, src/CommunityToolkit/Xamarin.CommunityToolkit.Sample.Android/Xamarin.CommunityToolkit.Sample.Android.csproj, src/CommunityToolkit/Xamarin.CommunityToolkit.Sample.GTK/Xamarin.CommunityToolkit.Sample.GTK.csproj, src/CommunityToolkit/Xamarin.CommunityToolkit.Sample.Tizen/Xamarin.CommunityToolkit.Sample.Tizen.csproj, src/CommunityToolkit/Xamarin.CommunityToolkit.Sample.UWP/Xamarin.CommunityToolkit.Sample.UWP.csproj, src/CommunityToolkit/Xamarin.CommunityToolkit.Sample.WPF/Xamarin.CommunityToolkit.Sample.WPF.csproj, src/CommunityToolkit/Xamarin.CommunityToolkit.Sample.iOS/Xamarin.CommunityToolkit.Sample.iOS.csproj, src/CommunityToolkit/Xamarin.CommunityToolkit.Sample/Xamarin.CommunityToolkit.Sample.csproj
###Changes###
- Fixed path to csprojs
- Added job to build samples sln
- Fixes #610
=> Fix Samples build

src/CommunityToolkit/Xamarin.CommunityToolkit/Views/StateLayout/StateLayoutController.shared.cs
Do not change children collection if the state changed during the animation
- Fixes #557 
None
None
=> StateLayout crashes when AnimateStateChanges is True

src/CommunityToolkit/Xamarin.CommunityToolkit/AssemblyInfo/AssemblyInfo.tizen.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Behaviors/RequiredStringValidationBehavior.shared.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/RemoveBorder/RemoveBorderEffect.shared.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/VisualFeedback/VisualFeedbackEffectRouter.ios.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Extensions/GravatarImageExtension.shared.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Helpers/PreserveToolkitAttribute.shared.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Views/AvatarView/ImageSourceValidator.android.ios.macos.uwp.wpf.gtk.tizen.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Views/GravatarImageSource/Android/GravatarImageSourceHandler.android.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Views/GravatarImageSource/GravatarImageSource.shared.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Views/GravatarImageSource/MacOS/GravatarImageSourceHandler.macos.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Views/GravatarImageSource/Shared/GravatarImageSourceHandler.android.ios.macos.tizen.uwp.wpf.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Views/GravatarImageSource/Shared/GravatarImageSourceHandler.ios.macos.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Views/GravatarImageSource/Tizen/GravatarImageSourceHandler.tizen.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Views/GravatarImageSource/UWP/GravatarImageSourceHandler.uwp.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Views/GravatarImageSource/Wpf/GravatarImageSourceHandler.wpf.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Views/GravatarImageSource/iOS/GravatarImageSourceHandler.ios.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Views/MediaElement/MediaElement.shared.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Views/Snackbar/Helpers/iOS/SnackBarAppearance.ios.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Views/Snackbar/Helpers/iOS/SnackbarViews/ActionMessageSnackBarView.ios.cs
Only project cleanup (Mostly changed files encoding to UTF-8 with BOM)
None
None
=> [Housekeeping] Warnings elimination

src/CommunityToolkit/Xamarin.CommunityToolkit.Sample/Pages/Views/UniformGridPage.xaml, src/CommunityToolkit/Xamarin.CommunityToolkit.Sample/Pages/Views/UniformGridPage.xaml.cs, src/CommunityToolkit/Xamarin.CommunityToolkit.Sample/ViewModels/Views/ViewsGalleryViewModel.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Views/UniformGrid.shared.cs
The UniformGrid is just like the Grid, with the possibility of multiple rows and columns, but with one important difference:
- All rows and columns will have the same size.
- Use this when you need the Grid behavior without the need to specify different sizes for the rows and columns.
Added: 
- `class UniformGrid`
=> UniformGrid

src/CommunityToolkit/Xamarin.CommunityToolkit/Views/CameraView/iOS/FormsCameraView.ios.cs
Fixes null reference exception for simulators appeared in #616 
- Fixes #614
None
None
=> Fixes CameraView iOS simulator NullReferenceException

README.md
This just fix the link on README that redirects to the sample
=> Fixed link to the sample

samples/XCT.Sample.sln
A small fix to make able to deploy the sample project in android devices.
- Related to #529
=> Added android in the Deploy configuration

samples/XCT.Sample.Android/Xamarin.CommunityToolkit.Sample.Android.csproj, samples/XCT.Sample.GTK/Xamarin.CommunityToolkit.Sample.GTK.csproj, samples/XCT.Sample.UWP/Xamarin.CommunityToolkit.Sample.UWP.csproj, samples/XCT.Sample.WPF/Xamarin.CommunityToolkit.Sample.WPF.csproj, samples/XCT.Sample.iOS/Xamarin.CommunityToolkit.Sample.iOS.csproj, samples/XCT.Sample/Xamarin.CommunityToolkit.Sample.csproj, src/CommunityToolkit/Xamarin.CommunityToolkit/Xamarin.CommunityToolkit.csproj, src/Markup/Xamarin.CommunityToolkit.Markup/Xamarin.CommunityToolkit.Markup.csproj
Hooray! It's here! This means we can launch too... 🚀 
Please check if I got all the NuGet references and a quick check if everything still works as intended :D
=> Update Forms dependency to Forms 5 stable

src/CommunityToolkit/Xamarin.CommunityToolkit/Xamarin.CommunityToolkit.csproj
Missed a couple of Forms 5 dependencies that needed updating
=> Missing Forms 5 Dependency updates

samples/XCT.Sample/Pages/Effects/TouchEffectPage.xaml, samples/XCT.Sample/Pages/Effects/TouchEffectPage.xaml.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/Touch/GestureManager.shared.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/Touch/PlatformTouchEffect.ios.cs
Implemented Hover API for iOS via UIHoverGestureRecognizer.
For testing, please run the test sample on the iPad simulator and enable pointers 
- Fixes #733 
None
Hover API work on IOS
=> [iOS] TouchEffect: Implemented hover handling

.github/PULL_REQUEST_TEMPLATE.md
Just an update on our PR Template.
=> Update PR template with branch info.

samples/XCT.Sample.Tizen/Main.cs, samples/XCT.Sample.UWP/App.xaml.cs, samples/XCT.Sample.UWP/MainPage.xaml.cs, samples/XCT.Sample.UWP/Properties/AssemblyInfo.cs, samples/XCT.Sample.WPF/Properties/AssemblyInfo.cs, samples/XCT.Sample/Helpers/MarkupExtensions.cs, samples/XCT.Sample/Pages/Behaviors/RequiredStringValidationBehaviorPage.xaml.cs, samples/XCT.Sample/Pages/Views/UniformGridPage.xaml.cs, samples/XCT.Sample/ViewModels/Effects/EffectsGalleryViewModel.cs, src/CommunityToolkit/Xamarin.CommunityToolkit.UnitTests/Converters/DateTimeOffsetConverter_Tests.cs
Fixed all style related warnings in sample app.
Also we need to replace spaces with tabs everywhere cause it's a mix of them right now. 
None
None
=> Fix style warnings in Sample app

src/CommunityToolkit/Xamarin.CommunityToolkit/Behaviors/UserStoppedTypingBehavior.shared.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Views/AvatarView/AvatarView.shared.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Views/AvatarView/ColorTheme.shared.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Views/AvatarView/IColorTheme.shared.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Views/BadgeView/BadgeAnimation.shared.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Views/BadgeView/BadgePosition.shared.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Views/BadgeView/BadgeView.shared.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Views/BadgeView/IBadgeAnimation.shared.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Views/BaseTemplatedView.shared.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Views/DockLayout/Dock.shared.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Views/DockLayout/DockLayout.shared.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Views/Shield.shared.cs
Added full comments for all public members on `AvatarView` (and associated), `BadgeView` (and associated), `DockLayout` (and associated), `UserStoppedTypingBehavior` and `Shield`
- Related #76 
N/A
People will be much happier in life now that they have some comments in the IntelliSense and ultimately on a documentation page
N/A
=> Adding first batch of code comments

samples/XCT.Sample/Pages/Views/ShieldPage.xaml, src/CommunityToolkit/Xamarin.CommunityToolkit/Views/Shield.shared.cs
Make Shield subject more customizable, details in issue.
closes #862
Please refer to linked issue.
=> Make ShieldView more customizable

src/CommunityToolkit/Xamarin.CommunityToolkit/Behaviors/BaseBehavior.shared.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Behaviors/EventToCommandBehavior.shared.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Behaviors/ImpliedOrderGridBehavior.shared.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Behaviors/MaskedBehavior.shared.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Behaviors/Validators/CharacterType.shared.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Behaviors/Validators/CharactersValidationBehavior.shared.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Behaviors/Validators/EmailValidationBehavior.shared.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Behaviors/Validators/MultiValidationBehavior.shared.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Behaviors/Validators/NumericValidationBehavior.shared.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Behaviors/Validators/RequiredStringValidationBehavior.shared.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Behaviors/Validators/TextDecorationFlags.shared.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Behaviors/Validators/TextValidationBehavior.shared.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Behaviors/Validators/UriValidationBehavior.shared.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Behaviors/Validators/ValidationBehavior.shared.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Xamarin.CommunityToolkit.csproj
Add inline comments/docs for all behaviors and associated types
- Related #76 
NA
Developers all around the world are delighted by the wonderful and clear descriptions they find in their IntelliSense
=> Document all behaviors and associated

src/CommunityToolkit/Xamarin.CommunityToolkit/Converters/BoolToObjectConverter.shared.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Converters/ByteArrayToImageSourceConverter.shared.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Converters/DateTimeOffsetConverter.shared.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Converters/DoubleToIntConverter.shared.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Converters/EqualConverter.shared.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Converters/IndexToArrayItemConverter.shared.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Converters/IntToBoolConverter.shared.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Converters/InvertedBoolConverter.shared.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Converters/IsNotNullOrEmptyConverter.shared.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Converters/IsNullOrEmptyConverter.shared.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Converters/ItemSelectedEventArgsConverter.shared.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Converters/ItemTappedEventArgsConverter.shared.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Converters/ListIsNotNullOrEmptyConverter.shared.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Converters/ListIsNullOrEmptyConverter.shared.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Converters/ListToStringConverter.shared.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Converters/MultiConverter.shared.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Converters/MultiConverterParameter.shared.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Converters/NotEqualConverter.shared.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Converters/StateToBooleanConverter.shared.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Converters/TextCaseConverter.shared.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Converters/TextCaseType.shared.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Converters/TimeSpanToDoubleConverter.shared.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Converters/VariableMultiValueConverter.shared.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Helpers/MultiBindingCondition.shared.cs
Adds inline Docs and comments to all the Converters and things that have to do with it
- Related #76 
NA
A Gerald statue will be erected by the people who love the converters but didn't know how to use them until now.
=> Add inline Docs/Comments to Converters

src/CommunityToolkit/Xamarin.CommunityToolkit/Views/CameraView/iOS/FormsCameraView.ios.cs
Fixed the null check in the iOS FormsCameraView class. The `TakePhoto` method was checking whether the `videoOutput` was null. From what I understand, it should be checking the `photoOutput` since that's what it's using, so I fixed it.
No tests added/modified since this is a very minor change.
No samples added/modified since this is a very minor change.
None
None
None
=> Fix null check in the iOS FormsCameraView

azure-pipelines.yml
Tweak conditions for signing artifacts
=> Fix build signing

samples/XCT.Sample.iOS/Main.cs, samples/XCT.Sample/Pages/Converters/BoolToObjectConverterPage.xaml, samples/XCT.Sample/Pages/Converters/BoolToObjectConverterPage.xaml.cs, samples/XCT.Sample/Pages/Converters/DoubleToIntConverterPage.xaml, samples/XCT.Sample/Pages/Converters/DoubleToIntConverterPage.xaml.cs, samples/XCT.Sample/Pages/Converters/EqualConverterPage.xaml, samples/XCT.Sample/Pages/Converters/EqualConverterPage.xaml.cs, samples/XCT.Sample/Pages/Converters/IndexToArrayItemConverterPage.xaml, samples/XCT.Sample/Pages/Converters/IndexToArrayItemConverterPage.xaml.cs, samples/XCT.Sample/Pages/Converters/IntToBoolConverterPage.xaml, samples/XCT.Sample/Pages/Converters/IntToBoolConverterPage.xaml.cs, samples/XCT.Sample/Pages/Converters/InvertedBoolConverterPage.xaml, samples/XCT.Sample/Pages/Converters/InvertedBoolConverterPage.xaml.cs, samples/XCT.Sample/Pages/Converters/IsNotNullOrEmptyConverterPage.xaml, samples/XCT.Sample/Pages/Converters/IsNotNullOrEmptyConverterPage.xaml.cs, samples/XCT.Sample/Pages/Converters/IsNullOrEmptyConverterPage.xaml, samples/XCT.Sample/Pages/Converters/IsNullOrEmptyConverterPage.xaml.cs, samples/XCT.Sample/Pages/Converters/ListIsNotNullOrEmptyConverterPage.xaml, samples/XCT.Sample/Pages/Converters/ListIsNotNullOrEmptyConverterPage.xaml.cs, samples/XCT.Sample/Pages/Converters/ListToStringConverterPage.xaml, samples/XCT.Sample/Pages/Converters/ListToStringConverterPage.xaml.cs, samples/XCT.Sample/Pages/Converters/NotEqualConverterPage.xaml, samples/XCT.Sample/Pages/Converters/NotEqualConverterPage.xaml.cs, samples/XCT.Sample/Pages/Converters/TextCaseConverterPage.xaml, samples/XCT.Sample/Pages/Converters/TextCaseConverterPage.xaml.cs, samples/XCT.Sample/ViewModels/Converters/ConvertersGalleryViewModel.cs, samples/XCT.Sample/ViewModels/Converters/DoubleToIntConverterViewModel.cs, samples/XCT.Sample/ViewModels/Converters/IndexToArrayItemConverterViewModel.cs, samples/XCT.Sample/ViewModels/Converters/IntToBoolConverterViewModel.cs, samples/XCT.Sample/ViewModels/Converters/IsNullOrEmptyConverterViewModel.cs
Added the Stated converters in #430 
Added missing Converters to sample app.
Code House Keeping
No api changes
=> Adding converter samples

src/CommunityToolkit/Xamarin.CommunityToolkit.UnitTests/Behaviors/MaxLengthReachedBehavior_Tests.cs, src/CommunityToolkit/Xamarin.CommunityToolkit.UnitTests/Behaviors/UserStoppedTypingBehavior_Tests.cs, src/CommunityToolkit/Xamarin.CommunityToolkit.UnitTests/Converters/DoubleToIntConverter_Tests.cs, src/CommunityToolkit/Xamarin.CommunityToolkit.UnitTests/Converters/EnumToBoolConverter_Tests.cs, src/CommunityToolkit/Xamarin.CommunityToolkit.UnitTests/Converters/ItemSelectedEventArgsConverter_Tests.cs, src/CommunityToolkit/Xamarin.CommunityToolkit.UnitTests/Converters/ItemTappedEventArgsConverter_Tests.cs, src/CommunityToolkit/Xamarin.CommunityToolkit.UnitTests/Converters/ListIsNotNullOrEmptyConverter_Tests.cs, src/CommunityToolkit/Xamarin.CommunityToolkit.UnitTests/Converters/ListIsNullOrEmptyConverter_Tests.cs, src/CommunityToolkit/Xamarin.CommunityToolkit.UnitTests/Converters/ListToStringConverter_Tests.cs, src/CommunityToolkit/Xamarin.CommunityToolkit.UnitTests/EnableInitOnlyProperties.cs, src/CommunityToolkit/Xamarin.CommunityToolkit.UnitTests/Helpers/LocalizationResourceManagerTests/LocalizationResourceManagerTests.cs, src/CommunityToolkit/Xamarin.CommunityToolkit.UnitTests/Helpers/LocalizedStringTests/LocalizedStringTests.cs, src/CommunityToolkit/Xamarin.CommunityToolkit.UnitTests/Helpers/WeakEventManagerTests/WeakEventManager_ActionT_Tests.cs, src/CommunityToolkit/Xamarin.CommunityToolkit.UnitTests/Helpers/WeakEventManagerTests/WeakEventManager_EventHandlerT_Tests.cs, src/CommunityToolkit/Xamarin.CommunityToolkit.UnitTests/Mocks/MockPlatformServices.cs, src/CommunityToolkit/Xamarin.CommunityToolkit.UnitTests/Mocks/MockResourceManager.cs, src/CommunityToolkit/Xamarin.CommunityToolkit.UnitTests/Namespace_Tests.cs, src/CommunityToolkit/Xamarin.CommunityToolkit.UnitTests/ObjectModel/ICommandTests/AsyncCommandTests/AsyncCommand_Tests.cs, src/CommunityToolkit/Xamarin.CommunityToolkit.UnitTests/ObjectModel/ICommandTests/AsyncCommandTests/IAsyncCommand_Tests.cs, src/CommunityToolkit/Xamarin.CommunityToolkit.UnitTests/ObjectModel/ICommandTests/AsyncCommandTests/ICommand_AsyncCommand_Tests.cs, src/CommunityToolkit/Xamarin.CommunityToolkit.UnitTests/ObjectModel/ICommandTests/AsyncValueCommandTests/AsyncValueCommand_Tests.cs, src/CommunityToolkit/Xamarin.CommunityToolkit.UnitTests/ObjectModel/ICommandTests/AsyncValueCommandTests/ICommand_AsyncValueCommand_Tests.cs, src/CommunityToolkit/Xamarin.CommunityToolkit.UnitTests/ObjectModel/ICommandTests/CommandFactoryTests/CommandFactory_AsyncCommand_Tests.cs, src/CommunityToolkit/Xamarin.CommunityToolkit.UnitTests/ObjectModel/ICommandTests/CommandFactoryTests/CommandFactory_AsyncValueCommand_Tests.cs, src/CommunityToolkit/Xamarin.CommunityToolkit.UnitTests/ObjectModel/ICommandTests/CommandFactoryTests/CommandFactory_Command_Tests.cs, src/CommunityToolkit/Xamarin.CommunityToolkit.UnitTests/ObjectModel/ObservableObject_Tests.cs, src/CommunityToolkit/Xamarin.CommunityToolkit.UnitTests/ObjectModel/ObservableRangeCollection_Tests.cs, src/CommunityToolkit/Xamarin.CommunityToolkit.UnitTests/ObjectModel/Person.cs, src/CommunityToolkit/Xamarin.CommunityToolkit.UnitTests/Views/MediaSource_Tests.cs, src/CommunityToolkit/Xamarin.CommunityToolkit.UnitTests/Xamarin.CommunityToolkit.UnitTests.csproj
This PR Enables Nullable on `Xamarin.CommunityToolkit.UnitTests`
=> Enable Nullable on Unit Tests

src/CommunityToolkit/Xamarin.CommunityToolkit/Views/Popup/iOS/PopupRenderer.ios.cs
=> [iOS] Fix missing binding context for popup view

src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/Touch/PlatformTouchEffect.android.cs
=> [Android] Fix regression in TouchEffect

samples/XCT.Sample/ViewModels/Converters/ItemSelectedEventArgsViewModel.cs
=> Fix typo in converter example

src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/RemoveBorder/RemoveBorderEffect.ios.cs
I upgraded from 1.0.3 to 1.1.0 and suddenly was getting a `System.InvalidCastException` being thrown from this effect.
Here is the stack trace:
```
at Xamarin.CommunityToolkit.iOS.Effects.RemoveBorderEffect.get_TextField () [0x00006] in <ed56dc24dfeb4b7cbd0f7272b792096c>:0 
at Xamarin.CommunityToolkit.iOS.Effects.RemoveBorderEffect.OnAttached () [0x00000] in <ed56dc24dfeb4b7cbd0f7272b792096c>:0 
at Xamarin.Forms.Effect.SendAttached () [0x00009] in D:\a\1\s\Xamarin.Forms.Core\Effect.cs:54 
at Xamarin.Forms.RoutingEffect.SendAttached () [0x00000] in D:\a\1\s\Xamarin.Forms.Core\RoutingEffect.cs:29 
```
Although the git history doesn't show me in here, I added this effect back to the toolkit in #492 and I originally cast the `Control` using `as` instead of a hard cast. This was to guard from …
=> Fix Invalid Cast Exception on iOS

src/CommunityToolkit/Xamarin.CommunityToolkit/Views/SideMenuView/SideMenuView.shared.cs
Restore changes that were missed during merging main and develop branches
Includes combined changes of:
https://github.com/xamarin/XamarinCommunityToolkit/pull/1192
https://github.com/xamarin/XamarinCommunityToolkit/pull/1250
None
None
=> [SideMenuView] Fixes after merge

src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/Touch/GestureManager.shared.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/Touch/TouchEffect.shared.cs
Added Element's null check before calling IsAvailable
- Fixes #1216 
None
None
=> [TouchEffect] Fix argument null exception

src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/Shadow/PlatformShadowEffect.android.cs
Implement custom outline provider for being possible drawing shadow in a rounded shape.
- Fixes #1298
None
None
=> [Android] Fix "ShadowEffect's shadow doesn't follow button's perimeter"

src/CommunityToolkit/Xamarin.CommunityToolkit/Views/Popup/BasePopup.shared.cs
Updates xml docs for popup's light dismiss property
- Fixes #1363 
N/A 
N/A
=> Updated light dismiss xml docs

src/CommunityToolkit/Xamarin.CommunityToolkit/Views/TabView/TabView.shared.cs
The old position and new position in the SelectionChanged event was always the same
- Fixes #1208
=> Fix oldPosition newPostion args issue

samples/XCT.Sample/App.xaml
In #1416 I changed the CollectionView to a ListView to fix things on UWP, but now the sample app looked broken on iOS and Android. Added this new stuff to make it look visually appealing again :)
=> Fix Sample App Visual on iOS and Android

samples/XCT.Sample.WPF/DrawingViewRenderer.wpf.cs, samples/XCT.Sample/Pages/Views/DrawingViewPage.xaml, src/CommunityToolkit/Xamarin.CommunityToolkit/Views/DrawingView/DrawingView.shared.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Views/DrawingView/Renderer/DrawingViewRenderer.android.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Views/DrawingView/Renderer/DrawingViewRenderer.gtk.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Views/DrawingView/Renderer/DrawingViewRenderer.ios.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Views/DrawingView/Renderer/DrawingViewRenderer.macos.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Views/DrawingView/Renderer/DrawingViewRenderer.tizen.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Views/DrawingView/Renderer/DrawingViewRenderer.uwp.cs
Fixes 
- Fixes #1452,
- Fixes #1453
- Fixes #1451 
LineColor is set to Black, Enable SmoothLine by default
=> Drawing view fixes

src/CommunityToolkit/Xamarin.CommunityToolkit/Views/Expander/Expander.shared.cs
Remove redundant line which somehow appeared again after removal in #1147
None
None
- [] Has tests (if omitted, state reason in description)
=> Fixes Expander Direction regression bug

samples/XCT.Sample/Pages/Views/SnackBarPage.xaml.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Extensions/VisualElement/VisualElementExtension.shared.cs
- Fixes #1496 
Corner Radius is applied for toasts
=> Fix Toast CornerRadius

samples/XCT.Sample/Pages/Views/DrawingViewPage.xaml, samples/XCT.Sample/Pages/Views/DrawingViewPage.xaml.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Views/DrawingView/Renderer/DrawingViewRenderer.ios.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Views/DrawingView/Renderer/DrawingViewRenderer.macos.cs
- Fixes #1495 
Clear DrawingView on Clear Lines
=> iOS, macOS - Clean DrawingView on Lines clean

src/CommunityToolkit/Xamarin.CommunityToolkit/Views/CameraView/iOS/FormsCameraView.ios.cs
I would like to remove unused code to make it easier to maintain, starting from `FormsCameraView`.
- Fixes #1587 
Removed:
- `UIImage RotateImage(UIImage image)`
NA
=> [CameraView][iOS] Remove unused code

src/CommunityToolkit/Xamarin.CommunityToolkit/Views/Popup/BasePopup.shared.cs
This simply corrects some typos discovered when documenting the `Popup` control.
N/A
N/A
=> Fixed typos in Popup XML docs

.github/ISSUE_TEMPLATE/maui_compat_bug_report_template.md
I missed the fact that the maui compat issue template would appear higher up in the list above general Bug Report. I have also modified the details so that it is more consistent with the maui repo.
To double check this now you can view these changes in action on my fork:
https://github.com/bijington/XamarinCommunityToolkit/issues/new/choose
=> Move down the list and make title consist with maui repo

src/CommunityToolkit/Xamarin.CommunityToolkit/Views/Snackbar/Helpers/iOS/SnackbarViews/BaseSnackBarView.ios.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Views/Snackbar/Helpers/iOS/SnackbarViews/MessageSnackBarView.ios.cs
=> 1777 Snackbar button is missed

MauiCompat.sh, azure-pipelines.yml
=> MauiCompat Fix for preview 12

azure-pipelines.yml, src/CommunityToolkit/Xamarin.CommunityToolkit/Views/DrawingView/Extensions/Extensions.shared.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Views/DrawingView/Renderer/DrawingViewRenderer.android.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Views/DrawingView/Renderer/DrawingViewRenderer.gtk.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Views/DrawingView/Renderer/DrawingViewRenderer.ios.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Views/DrawingView/Renderer/DrawingViewRenderer.macos.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Views/DrawingView/Renderer/DrawingViewRenderer.tizen.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Views/DrawingView/Renderer/DrawingViewRenderer.uwp.cs
- Fixes #1822
because of smoothing collection of points changed each time the user draws the line. as a result, led to more than 1 million points which took time to process. We shouldn't change the original (drawn) collection of points but should smooth the path only to visualize it. 
The fix also includes enabling smoothing for all platforms (previously it was only for iOS/macOS) and minor nullable leftovers
=> 1822 DrawingView fix freezing

azure-pipelines.yml, src/CommunityToolkit/Xamarin.CommunityToolkit/Views/Popup/UWP/PopupRenderer.uwp.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Xamarin.CommunityToolkit.csproj
=> Cleanup pipeline

MauiCompatSteps.md
which make the zsh script looking wired in markdown output.
- Fixes #
=> fix the code formatting indentation error

src/CommunityToolkit/Xamarin.CommunityToolkit/Views/CameraView/Android/CameraFragment.android.cs
The CameraView does not trigger the flashlight after the first capture even keeping the FlashMode as On.
- Fixes #1863 
```
if (flashMode == FlashMode.Single)
{
sessionBuilder.Set(CaptureRequest.FlashMode ?? throw new NullReferenceException(), (int)FlashMode.Off);
session.Capture(sessionBuilder.Build(), null, null);
}
```
=> CameraView Flash fix for Android

samples/XCT.Sample/Pages/TestCases/Issue1883.xaml, samples/XCT.Sample/Pages/TestCases/Issue1883.xaml.cs, samples/XCT.Sample/Pages/Views/SnackBarPage.xaml, samples/XCT.Sample/Pages/Views/SnackBarPage.xaml.cs, samples/XCT.Sample/ViewModels/TestCases/TestCasesGalleryViewModel.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Views/MediaElement/iOS/MediaElementRenderer.ios.cs, src/CommunityToolkit/Xamarin.CommunityToolkit/Views/Snackbar/Helpers/iOS/SnackbarViews/ActionMessageSnackBarView.ios.cs
=> Issue 1883 Snackbar button is missed

azure-pipelines.yml, src/CommunityToolkit/Xamarin.CommunityToolkit/Views/MediaElement/MacOS/MediaElementRenderer.macos.cs
=> Update macOS build image
