xamarin/XamarinCommunityToolkit

src/Effects/Effects.iOS/Effects/Label/LabelCustomFont.cs

This code fixes #25.
It is a bug of built-in behaviour in Xamarin.iOS,
as seen on their [bug
tracker](https://bugzilla.xamarin.com/show_bug.cgi?id=33666). After
each change of certain properties (TextColor, Font, Text or
FormattedText) the effect is reapplied.
Please take a moment to fill out the following:

Fix for #25

---

Samples/Samples/Views/EffectsEntryRemoveBorderPage.xaml

Fixes #87.
Remove a character that causes an exception to be thrown when opening the Entry effects' "Remove border entry" page.

Remove extra character causing a crash

---

XamarinCommunityToolkit/XamarinCommunityToolkit.csproj

Like it says in the title! Let's start out with a low dependency and see if we need to move up whenever we need something specific in newer Forms versions.
This should also fix the build error we're seeing right now

Lower Forms dependency to 3.5

---

XamarinCommunityToolkit/Converters/BoolToObjectConverter.shared.cs
XamarinCommunityToolkit/Converters/DoubleToIntConverter.shared.cs
XamarinCommunityToolkit/Converters/EqualConverter.shared.cs
XamarinCommunityToolkit/Converters/IndexToArrayItemConverter.shared.cs
XamarinCommunityToolkit/Converters/IntToBoolConverter.shared.cs
XamarinCommunityToolkit/Converters/InvertedBoolConverter.shared.cs
XamarinCommunityToolkit/Converters/IsNotNullOrEmptyConverter.shared.cs
XamarinCommunityToolkit/Converters/IsNullOrEmptyConverter.shared.cs
XamarinCommunityToolkit/Converters/ListIsNotNullOrEmptyConverter.shared.cs
XamarinCommunityToolkit/Converters/ListIsNullOrEmptyConverter.shared.cs
XamarinCommunityToolkit/Converters/NotEqualConverter.shared.cs
XamarinCommunityToolkit/Converters/TextCaseConverter.shared.cs
XamarinCommunityToolkit/Converters/TextCaseType.shared.cs
XamarinCommunityToolkit/Converters/ValueConverterMarkupExtension.shared.cs
XamarinCommunityToolkit/Extensions/ValueConverterExtension.shared.cs
XamarinCommunityToolkit/XamarinCommunityToolkit.csproj

Implemented IMarkupExtension for converters.
Now they can be used as:
```xaml
<Label Text="{Binding MyString, Converter={kit:TextCaseConverter Upper}}" />
```
Since default interface implementations are not supported by nestandard 1 and 2 we **cannot** use them. So I decided to go ahead with the abstract class.
Also, I had to add *System.ComponentModel* nuget for nestandard1.0 **only** due to nestandard1.0 needs (IServiceProvider is presented there)
- Related to issue #133 
None

Implement IMarkupExtension in converters

---

XamarinCommunityToolkit/Converters/MultiConverter.shared.cs
XamarinCommunityToolkit/Converters/MultiConverterParameter.shared.cs

This is a converter that allows for multiple converters to be applied in series.
```
<ResourceDictionary>
<xct:MultiConverter x:Key="myMultiConverter">
<xct:TextCaseConverter />
<xct:NotEqualConverter />
</xct:MultiConverter>
<x:Array x:Key="multiParams" Type="{x:Type xct:MultiConverterParameter}">
<xct:MultiConverterParameter ConverterType="{x:Type xct:TextCaseConverter}" Value="{x:Static xct:TextCaseConverterType.Upper}" />
<xct:MultiConverterParameter ConverterType="{x:Type xct:NotEqualConverter}" Value="ANDREI" />
</x:Array>
</ResourceDictionary>
```
In your control e.g.:
```
<Label Text="{Binding X, Converter={StaticResource myMultiConverter}, ConverterParameter={StaticResource multiParams}}"
VerticalOptions="CenterAndExpand" 
HorizontalOptions="CenterAndExpand" />
```
With a binding …

Multiconverter

---

XamarinCommunityToolkit/Behaviors/TextDecorationFlags.shared.cs
XamarinCommunityToolkit/Behaviors/TextValidationBehavior.shared.cs
XamarinCommunityToolkitSample/Pages/Behaviors/EmailValidationBehaviorPage.xaml

Replaces a bunch of properties by one "flags" property.
- Related to issue #149 
Added: 
- `TextDecorationFlags TextValidationBehavior.DecorationFlags { get; set; }`
- `TextDecorationFlags`
Removed:
- `bool TextValidationBehavior.ShouldTrimValue`
- `bool TextValidationBehavior.ShouldConvertNullToEmptyValue`
If there is an entirely new API, then you can use a more verbose style:
```csharp
[Flags]
public enum TextDecorationFlags
{
None = 0,
TrimStart = 1,
TrimEnd = 2,
Trim = 3,
NullToEmpty = 4,
ReduceWhiteSpaces = 8
}
```
More convenient for use (need to set up only one property with necessary flags instead of several)

TextDecorationFlags for TextValidationBehavior

---

XamarinCommunityToolkit.UnitTests/Behaviors/EventToCommandBehavior_Tests.cs
XamarinCommunityToolkit/Behaviors/EventToCommandBehavior.shared.cs

We should create event handler for observing the event according to **eventInfo.EventHandlerType**.
```csharp
eventHandler = eventHandlerMethodInfo.CreateDelegate(eventInfo.EventHandlerType, this)
```
- Related to issue #158 
None
No crash when used with ListView events

[Bug] EventToCommandBehavior throws ArgumentException

---

XamarinCommunityToolkit.UnitTests/Converters/ItemSelectedEventArgsConverter_Tests.cs
XamarinCommunityToolkit.UnitTests/Converters/ItemTappedEventArgsConverter_Tests.cs
XamarinCommunityToolkit/Converters/ItemSelectedEventArgsConverter.shared.cs
XamarinCommunityToolkitSample/Models/Converters/ConverterSectionId.cs
XamarinCommunityToolkitSample/Pages/Converters/ConvertersGalleryPage.xaml.cs
XamarinCommunityToolkitSample/Pages/Converters/ItemSelectedEventArgsPage.xaml
XamarinCommunityToolkitSample/Pages/Converters/ItemSelectedEventArgsPage.xaml.cs
XamarinCommunityToolkitSample/ViewModels/Converters/ItemSelectedEventArgsViewModel.cs
XamarinCommunityToolkitSample/ViewModels/Converters/ItemTappedEventArgsViewModel.cs

This is a very simple converter that allows you to extract `SelectedItem` value from `ItemSelectedEventArgs` object and it can be used in combination with `EventToCommandBehavior`.
Added: 
- `ItemSelectedEventArgsConverter`
```
<c:ItemSelectedEventArgsConverter x:Key="ItemSelectedEventArgsConverter" />
<ListView.Behaviors>
<b:EventToCommandBehavior EventName="ItemSelected" 
Command="{Binding ItemSelectedCommand}"
EventArgsConverter="{StaticResource ItemSelectedArgsConverter}" />
</ListView.Behaviors>   
```

Implement ItemSelectedEventArgsConverter in converters

---

XamarinCommunityToolkit.sln

The main solution file XamarinCommunityToolkit.sln has been fixed to reference the newly renamed project (Microsoft.Toolkit.Xamarin.Forms).
I've chosen to disregard the PR checklist for this PR since it doesn't really add any functionality.
No reported bugs, but I got an error when I tried to open the solution. The sample solution worked fine, so I just removed the project from the main solution and added the reference back with the new project name.
None.
None.

Fixed project reference for main solution

---

XamarinCommunityToolkit.sln

This is just a small fix to allow us to load the XamarinCommunity project using the `XamarinCommunityToolkit.sln`
Error:
"The project file cannot be found."

Fixed project name in solution file

---

CONTRIBUTING.md

Adding some detail to the proposal approval process per a discussion with @jfversluis

Add proposal approval process to contributor guide

---

XamarinCommunityToolkit/AssemblyInfo/AssemblyInfo.android.cs
XamarinCommunityToolkit/AssemblyInfo/AssemblyInfo.ios.tvos.watchos.macos.cs

Bring some of the linker love to this library, now the output dll is the same size in `Linker all` or` Link Framework SDKs Only`
As we discuss on the Discord server, we want this lib to be linker safe, this way devs don't need to use `Linker all` to strip out unused code.
Added two files inside the `AssemblyInfo` folder the LinkerSafe attribute in `Android` and `iOS` platform.
Added: 
` [assembly: LinkerSafe]`
Now when the build is configured to `Link Framework SDKs Only` the XamarinCommunityToolkit will remove unused code.
Test this isn't obvious so I'll describe how I validated this. I create a blank project and add the XamarinCommunityToolkit (XCT) to it, and just use one item from the lib.
```csharp 
var area = new Xamarin.CommunityToolkit.Helpers.SafeArea(); 
``` 
1. On my iOS …

Make Xamarin CommunityToolkit linker safe

---

XamarinCommunityToolkitSample.Android/Resources/values/styles.xml

Updated toolbar item color to #5D5D5D which matches `NavigationBarTextColor` from App.xaml.
Old color was white text on white background
@jfversluis once commented on a question about this that I encountered while fixing this, I gave it an upvote.
Changed the Toolbar background color.
Fixed #231 
None, sample code only
Users can now use Settings and About page without being psychic

Set android Toolbar item color

---

README.md

Noticed that the read me file says "Xamarin.CommunityToolkit.UI.Controls" not "Xamarin.CommunityToolkit.UI.Views" like is used in all the controls currently added.

[Housekeeping] Update README Controls namespace to Views to match actual implementation

---

XamarinCommunityToolkitSample/AssemblyInfo.cs

Added default language in sample app. Without this UWP has Null for all resources until a language is set.
Set NeutralResourcesLanguage to `en`
Fixes #230 
None
None

Set Default Language in UWP to fix blank text resources

---

XamarinCommunityToolkit.UnitTests/ConvertersNamespace_Tests.cs

Don't know if this makes any sense, but digging into the code the other day I noticed how easy it is to mix up namespaces. This will be especially true when working with extra subfolders like with `CameraView`.
Samples not added because... Tests.
If this does not make any sense to anyone, please tell me as well :D 
Or if you have ideas on how to add more checks like these.
N/A
N/A

Added some unit tests to check namespaces

---

XamarinCommunityToolkit.UnitTests/Behaviors/NumericValidationBehavior_Tests.cs
XamarinCommunityToolkit/Behaviors/Validators/NumericValidationBehavior.shared.cs

Use `CultureInfo.CurrentCulture.NumberFormat.NumberDecimalSeparator` in `NumericValidationBehavior`.
Not sure about the tests. Is this the way to go to test multiple cultures?
I didn't add additional samples and additional documentation.
- Related to issue #247 
No API changes
The `NumericValidationBehavior` takes now the current culture into account.
Previously, the '.' sign was hardcoded. Now the `CultureInfo.CurrentCulture.NumberFormat.NumberDecimalSeparator` is used.

use decimal separator from current culture

---

XamarinCommunityToolkit/Views/SideMenuView/SideMenuView.shared.cs
XamarinCommunityToolkitSample/Pages/Views/SideMenuViewPage.xaml
XamarinCommunityToolkitSample/Pages/Views/SideMenuViewPage.xaml.cs

Setting MenuGestureEnabled to False broke the possibility to set "State" manually.
**How to test:"
1) Run the sample app and navigate to SideMenuPage
2) Make sure you can open the right/left menu by dragging.
3) Set ```views:SideMenuView.MenuGestureEnabled="False"``` to any menu view
4) Restart the app and navigate to SideMenuPage again (Or probably HotReload will reload XAML for you)
5) Make sure you cannot open the menu by dragging anymore, but still can open the menu by clicking the button (||).
- Fixes #263
Provide links to issues here. Ensure that a GitHub issue was created for your feature or bug fix before sending PR.
None
None
- [] Has tests (if omitted, state reason in description)

[Bug] SideMenu: MenuGestureEnabled = False doesn't work

---

XamarinCommunityToolkit/Views/CameraView/Android/CameraFragment.android.cs

Fixed the method SetVideoStabilization of CameraFragment on Android.
The condition was invalid and should have been reversed.
- Fixes #303
None
VideoStabilization on Android should now be set.

[Bug] [CameraView] [Android] Fixed SetVideoStabilization of CameraFragment

---

XamarinCommunityToolkit/Views/CameraView/Android/CameraFragment.android.cs
XamarinCommunityToolkit/Views/CameraView/MediaCapturedEventArgs.shared.cs
XamarinCommunityToolkit/Views/CameraView/UWP/CameraViewRenderer.uwp.cs
XamarinCommunityToolkit/Views/CameraView/iOS/CameraViewRenderer.ios.cs
XamarinCommunityToolkit/Xamarin.CommunityToolkit.csproj

As stated in https://github.com/xamarin/XamarinCommunityToolkit/issues/287 it is sometimes necessary to access the path of the saved file.
Currently it's also impossible to access the video file because it has been moved and the path given to the MediaSource is invalid.
Furthermore I added a lazy creation of ImageSource/MediaSource since they are not always needed.
List all API changes here (or just put None), example:
Added in MediaCapturedEventArgs: 
- `string Path { get; }`
Changed in MediaCapturedEventArgs:
- `object Data { get; }` => `byte[] ImageData { get; }`
- `ImageSource Image` is now lazily created
- `MediaSource Video` is now lazily created
- `internal MediaCapturedEventArgs(object data = null, ImageSource image = null, MediaSource video = null)` => `internal …

CameraView: Implemented returning of path of saved file

---

XamarinCommunityToolkit/Views/CameraView/Android/CameraFragment.android.cs

Fixed the unnecessary request of RecordAudio permission when CaptureOptions is not CameraCaptureOptions.Video
- Fixes #296 
None.
Only asks for Microphone Access when CaptureOptions is CameraCaptureOptions.Video.

[Bug] [CameraView] [Android] Fixed unnecessary request of RecordAudio permission

---

XamarinCommunityToolkit/Views/CameraView/Android/CameraFragment.android.cs

The previous logic was mirroring twice if the CameraView got initialized with CameraOptions.Front.
This made the Android implementation work like the iOS implementation in this aspect.
- Fixes #295
None.
None.

[Bug] [CameraView] [Android] Removed unnecessary mirroring code

---

XamarinCommunityToolkit/Views/Expander/Expander.shared.cs

Expander's animation length cannot be set to zero (it causes a crash on Animation level)
That's why we always should coerce the animation length value to be non-zero (1 millisecond is pretty fast and from users perspective is not noticeable)
For testing go to ExpanderPage, set Expand/Collapse animation length to 0, then run the sample app and make sure crash does not happen anymore)
- Fixes #329 
None
None

Fixes "Expander - System.ArgumentException: 'NaN is not a valid value"

---

XamarinCommunityToolkit.UnitTests/Views/MediaElement_Tests.cs
XamarinCommunityToolkit/Views/MediaElement/MediaElement.shared.cs

The default value of ShowsPlaybackControls property was changed to **true**.
- Fixes https://github.com/xamarin/XamarinCommunityToolkit/issues/331
None
The playback controls will appear by default when using the control.

Change default value of ShowsPlaybackControls property

---

XamarinCommunityToolkit.UnitTests/ObjectModel/ObservableObject_Tests.cs
XamarinCommunityToolkit/ObjectModel/ObservableObject.shared.cs
XamarinCommunityToolkitSample/ViewModels/AboutViewModel.cs
XamarinCommunityToolkitSample/ViewModels/Base/BaseViewModel.cs
XamarinCommunityToolkitSample/ViewModels/Behaviors/EventToCommandBehaviorViewModel.cs
XamarinCommunityToolkitSample/ViewModels/Behaviors/UserStoppedTypingBehaviorViewModel.cs
XamarinCommunityToolkitSample/ViewModels/Converters/ByteArrayToImageSourceViewModel.cs
XamarinCommunityToolkitSample/ViewModels/Converters/DateTimeOffsetConverterViewModel.cs
XamarinCommunityToolkitSample/ViewModels/Converters/MultiConverterViewModel.cs
XamarinCommunityToolkitSample/ViewModels/SettingViewModel.cs
XamarinCommunityToolkitSample/ViewModels/Views/ExpanderViewModel.cs

Ive added the ObservableObject from MVVM Helpers
- Partial fixes
#190 
Added: 
```csharp
public abstract class ObservableObject
{
public event PropertyChangedEventHandler? PropertyChanged;
protected virtual void OnPropertyChanged([CallerMemberName] string propertyName = "");
protected virtual bool SetProperty<T>(ref T backingStore,
T value,
[CallerMemberName] string propertyName = "",
Action? onChanging = null,
Action? onChanged = null,
Func<T, T, bool>? validateValue = null);
}
```
Simple implementation of INotifyPropertyChanged that any class can inherit from.

Added ObservableObject from MVVM Helpers

---

XamarinCommunityToolkit/Extensions/TranslateExtension.shared.cs
XamarinCommunityToolkitSample.Android/Xamarin.CommunityToolkit.Sample.Android.csproj
XamarinCommunityToolkitSample.iOS/Xamarin.CommunityToolkit.Sample.iOS.csproj

I changed the Linker behavior in sample projects to the minimal, that way we can see when the linker removes bits.
@AndreiMisiukevich found this issue when he ran the sample project using linker at the minimum config.
```csharp
public class TranslateExtension{
public BindingBase ProvideValue(IServiceProvider serviceProvider)
{
#if !NETSTANDARD1_0
if (DateTime.Now.Ticks < 0)
_ = LocalizationResourceManager.Current[Text];
// rest of the code
}
```
Now the labels in `WelcomePage` appear.

Saving Localization Manager from Linker

---

XamarinCommunityToolkit/Views/CameraView/iOS/FormsCameraView.ios.cs

Caches the last camera position initialed and only reinitialize if the position changes.
Removes un-need init from FormsCamera ctor.
If camera permission must be asked for, after a successful granting of permission it retries camera init.
I tested in the sample app and now I only get 1 camera init to the default (back) using the sample.  If in the camera sample page xaml I set the camera option to "Front", I only get 1 camera init to the front camera.
As long as the camera option is set before the renderer is created, it should only result in 1 init.
Testing Procedure
* Set a breakpoint in FormsCameraView.RetrieveCameraDevice 
* Make sure it is only called once at startup. (previous behavior was called twice)
* Delete sample app from a device, redeploy and then make sure the camera …

Fix #286 Prevent extra iOS camera inits

---

XamarinCommunityToolkit/Effects/SafeAreaEffectRouter.shared.cs
XamarinCommunityToolkitSample/Pages/Effects/SafeAreaEffectPage.xaml
XamarinCommunityToolkitSample/Pages/Effects/SafeAreaEffectPage.xaml.cs

Now the linker keeps the SafeAreaEffect implementation into the `.dll` and the sample page doesn't throw an exception.
- Fixes #454 
- Fixes #393 
Added a static call to the SafeArea constructor.
Nothing breaks and everyone is happy.

Fix SafeAreaEffect

---

XamarinCommunityToolkit/Views/AvatarView/AvatarView.shared.cs
XamarinCommunityToolkitSample/Pages/Views/AvatarViewPage.xaml

Aligning FontSize property with the framework behavior for using NamedSize when declaring the view in Xaml.
- Fixes #471 
Changed:
- AvatarView :
Adding attribute `[TypeConverter(typeof(FontSizeConverter))]` to FontSize property

[AvatarView] Add the Attribute TypeConverter for NamedSize use

---

XamarinCommunityToolkit/Views/RangeSlider.shared.cs
XamarinCommunityToolkitSample/Pages/Views/RangeSliderPage.xaml

Added new events and property RangeSlider for easier observing drag status and selected value (Lower / Upper).
- Fixes #376 
```csharp
public event EventHandler ValueChanged;
public event EventHandler LowerValueChanged;
public event EventHandler UpperValueChanged;
public event EventHandler DragStarted;
public event EventHandler LowerDragStarted;
public event EventHandler UpperDragStarted;
public event EventHandler DragCompleted;
public event EventHandler LowerDragCompleted;
public event EventHandler UpperDragCompleted;
public double StepValue { get; set; }
```
None

RangeSlider: Added events and StepValue

---

XamarinCommunityToolkitSample/App.xaml
XamarinCommunityToolkitSample/ViewModels/Base/BaseGalleryViewModel.cs
XamarinCommunityToolkitSample/ViewModels/Behaviors/BehaviorsGalleryViewModel.cs
XamarinCommunityToolkitSample/ViewModels/Converters/ConvertersGalleryViewModel.cs
XamarinCommunityToolkitSample/ViewModels/Effects/EffectsGalleryViewModel.cs
XamarinCommunityToolkitSample/ViewModels/Views/ViewsGalleryViewModel.cs

Now you can filter sections in the galleries of the sample app.
It helps to find the needed page by filtering items source.
1) Focus entry
2) Input a part of **title** of the item you are looking for.
3) Press "Search"
4) **Filtered items appear**
**NOTE**: We don't filter items on TextChanged because we reload items in CollectionView what causes Search Entry focus resigning.
None
None

Sample app: Implemented filter for gallery pages

---

XamarinCommunityToolkit/Views/CameraView/CameraView.shared.cs

In a release build on iOS if you use the CameraView ShutterCommand, it was being linked away causing a binding failure and then not working.
Adds the preserve attribute to make sure command isn't linked away on iOS.  Should only be preserved if the CameraView class is also preserved.
- Fixes #503 - Not the cause of the native crash in 503, but is the cause of the Take Photo button not working in the sample app.

CameraView ShutterCommand Add Preserve Attribute

---

XamarinCommunityToolkit/Views/AvatarView/AvatarView.shared.cs
XamarinCommunityToolkitSample/Pages/Views/AvatarViewPage.xaml

Force reset Image's Source once its BindingContext changed 
- Fixes #512
None
None

Fixes AvatarView Source property binding

---

XamarinCommunityToolkit/Views/TabView/TabView.shared.cs
XamarinCommunityToolkitSample/Pages/Views/TabView/GettingStartedPage.xaml
XamarinCommunityToolkitSample/Pages/Views/TabView/TabPlacementPage.xaml

Added `TabStripBorderColor` property to TabView.
Added: 
- `Color TabView.TabStripBorderColor { get; set; }`

Added TabStripBorderColor property to TabView

---

XamarinCommunityToolkit/Behaviors/EventToCommandBehavior.shared.cs

Add a PreserveAttribute into the OnTriggerHandled method inside the class EventToCommandBehavior. Don't need unit tests.
Also Added a better error message if some user sees this error again.
- Fixes #426
Now we don't see any NRE exception related to the invocation of the control event. And now all devs will be happy!
The new error message

Prevent linker to remove OnTriggerHandled method

---

XamarinCommunityToolkitSample/App.xaml.cs
XamarinCommunityToolkitSample/Pages/Views/TabView/CustomTabsPage.xaml

Fixed wrong TabView icons path in UWP.
None
None

Fixed wrong UWP TabView icons path

---

XamarinCommunityToolkit/Views/TabView/TabView.shared.cs

Disable the CarouselView Loop used internally by the TabView in case of use Xamarin.Forms 5.0-pre3.
None
None

Update TabView behavior using Xamarin.Forms 5.0

---

XamarinCommunityToolkit/Views/SnackBar/Helpers/SnackBarLayout.uwp.wpf.cs

Set Snackbar Foreground text color for UWP and WPF from the `MessageOptions.Foreground`
None
None

Fixed Snackbar Foreground text color UWP-WPF

---

XamarinCommunityToolkit.UnitTests/Behaviors/EventToCommandBehavior_Tests.cs
XamarinCommunityToolkit/Behaviors/Animations/AnimationBehavior.shared.cs
XamarinCommunityToolkit/Behaviors/BaseBehavior.shared.cs
XamarinCommunityToolkit/Behaviors/EventToCommandBehavior.shared.cs
XamarinCommunityToolkit/Behaviors/Validators/ValidationBehavior.shared.cs

Allow using behaviors with VisualElements (Pages)
- Fixes #583
None
None

Fix "Cannot use EventToCommandBehavior for Page.Appearing event"

---

XamarinCommunityToolkit/Views/AvatarView/AvatarView.shared.cs

add a try/catch on the `await` call, inside the `async void OnValuePropertyChanged` method.
- Fixes #588

Fixed AvatarView crash

---

src/CommunityToolkit/Xamarin.CommunityToolkit.Sample/Pages/Views/AvatarViewPage.xaml

Added configuration to the page, so it uses iOS "Safe Area" and the Slider moves up into an area where it can be moved horizontally.
- Fixes #604 
Now users on iOS devices that shows the "Home indicator" instead of having a home button, can move the Slider horizontally.
**Before:**
**After:**

Fixes #604

---

src/CommunityToolkit/Xamarin.CommunityToolkit.Sample/Xamarin.CommunityToolkit.Sample.csproj

Xamarin.CommunityToolkit.Sample project build fix.
Change the path in https://github.com/xamarin/XamarinCommunityToolkit/blob/19616fd3666456458d4eb368b396f163591a0866/src/CommunityToolkit/Xamarin.CommunityToolkit.Sample/Xamarin.CommunityToolkit.Sample.csproj#L107 to `<ProjectReference Include="..\Xamarin.CommunityToolkit\Xamarin.CommunityToolkit.csproj" />`
- Fixes #611

Path fix in Xamarin.CommunityToolkit.Sample.csproj

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Views/RangeSlider/RangeSlider.shared.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/RangeSlider/ThumbFrame.shared.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/RangeSlider/ThumbFrameRenderer.android.cs

We should call RequestDisallowInterceptTouchEvent when the user interacts with thumbs (move them) for preventing scrolling on Android.
I added an internal class ThumbFrame that has a custom renderer for android where we prevent scrolling if a user drags it.
- Fixes #502 
None
None (only bugfix)

RangeSlider in Scrollview (Android)

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Views/AvatarView/AvatarView.shared.cs

The bug was introduced during fixing another bug in https://github.com/xamarin/XamarinCommunityToolkit/pull/465
We should force Image to fill all space in case Aspect has value AspectFill or Fill.
So, we preserve existing behavior for AspectFit but return back to initial behavior for Fill options.
- Fixes #599 
None
The image will be spread over the all space that is taken by its Frame.

[Bug] AvatarView Aspect

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Views/Snackbar/SnackBar.android.cs

Use pixels instead of points. Now it is consistent with other platforms
Partially fix #607

Fix Android font size

---

src/CommunityToolkit/Xamarin.CommunityToolkit.Sample/Pages/Views/DockLayoutPage.xaml
src/CommunityToolkit/Xamarin.CommunityToolkit.Sample/Pages/Views/DockLayoutPage.xaml.cs
src/CommunityToolkit/Xamarin.CommunityToolkit.Sample/ViewModels/Views/ViewsGalleryViewModel.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/DockLayout.shared.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/DockLayout/Dock.shared.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/DockLayout/DockLayout.shared.cs

The DockLayout makes it easy to dock content in all four directions (top, bottom, left and right). 
This makes it a great choice in many situations, where you want to divide the screen into specific areas, 
especially because by default, the last element inside the DockLayout, unless this feature is specifically disabled, 
will automatically fill the rest of the space (center).
Added: 
- DockLayout
```
<layout:DockLayout
LastChildFill="False">
<Button layout:DockLayout.Dock="Top" Text="Top" HeightRequest="50"/>
<Button layout:DockLayout.Dock="Bottom" Text="Bottom" HeightRequest="50"/>
<Button layout:DockLayout.Dock="Left" Text="Left" WidthRequest="60"/>
<Button layout:DockLayout.Dock="Left" Text="Left" WidthRequest="60"/>
<Button layout:DockLayout.Dock="Right" Text="Right" …
```

DockLayout

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Views/CameraView/iOS/FormsCameraView.ios.cs

@jfversluis reported a crash with the attached stack trace
[message (1).txt](https://github.com/xamarin/XamarinCommunityToolkit/files/5628842/message.1.txt)
Try to fix this crash
None
None

Try to fix iOS camera view crash on Dispose

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Views/BadgeView/BadgeView.shared.cs

BadgeIndicatorContainer should be invisible by default because the default text value is "0".
Also, we should call UpdateBadgeViewPlacement when BadgeIndicatorContainer visibility or BadgeText value changed for aligning the badge inside the view.
- Fixes #638 
None
If the initial value is 0, the badgeview will be hidden (Not it's visible, but it's bug)

Fixes BadgeView BadgeIndicatorContainer is visible if the Text property is 0 at the start

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Views/CameraView/iOS/FormsCameraView.ios.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/MediaElement/iOS/MediaElementRenderer.ios.cs

Changed the clean-up of the control to `Dispose` method.
For future references, when we have an observer like this:
`avPlayerViewController?.Player?.RemoveObserver(volumeObserver, "volume");` where we need to specify a key, we can't remove it and after Dispose it (e.g. `volumeObserver.Dispose()`) because that will lead an exception. If you just remove the observer (`RemoveObserver(volumeObserver, "volume")`) you will see in the output that you don't dipose it, and maybe this object can be alive in the memory (I guess). But if you just call the Dispose method (`volumeObserver.Dispose()`) nothing breaks and you don't see the warning in the output window.
- Fixes #558

Fixed fatal error on media element

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Views/GravatarImageSource/Shared/GravatarImageSourceHandler.android.ios.macos.tizen.uwp.wpf.cs

We must refresh FileInfo after saving content by file's path otherwise FileInfo instance will return **False** for **Exists** property.
- Fixes #526
None
None

Fixes GravatarImageSource doesn't work first time

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Views/MediaElement/iOS/MediaElementRenderer.ios.cs

Prevent restarting all media elements videos when any of them is played to end and is going to restart.
- Fixes #596
None
None

Fixes "MediaElement with IsLooping="True" restarting all videos"

---

Xamarin.CommunityToolkit.MarkupSample.sln
src/CommunityToolkit/Xamarin.CommunityToolkit.Sample.Android/Xamarin.CommunityToolkit.Sample.Android.csproj
src/CommunityToolkit/Xamarin.CommunityToolkit.Sample.GTK/Xamarin.CommunityToolkit.Sample.GTK.csproj
src/CommunityToolkit/Xamarin.CommunityToolkit.Sample.UWP/Xamarin.CommunityToolkit.Sample.UWP.csproj
src/CommunityToolkit/Xamarin.CommunityToolkit.Sample.WPF/Xamarin.CommunityToolkit.Sample.WPF.csproj
src/CommunityToolkit/Xamarin.CommunityToolkit.Sample.iOS/Xamarin.CommunityToolkit.Sample.iOS.csproj
src/CommunityToolkit/Xamarin.CommunityToolkit.Sample/Xamarin.CommunityToolkit.Sample.csproj
src/CommunityToolkit/Xamarin.CommunityToolkit/Xamarin.CommunityToolkit.csproj
src/Markup/Xamarin.CommunityToolkit.Markup/Xamarin.CommunityToolkit.Markup.csproj
src/Markup/Xamarin.CommunityToolkit.MarkupSample.UWP/Xamarin.CommunityToolkit.MarkupSample.UWP.csproj
src/Markup/Xamarin.CommunityToolkit.MarkupSample.iOS/Xamarin.CommunityToolkit.MarkupSample.iOS.csproj
src/Markup/Xamarin.CommunityToolkit.MarkupSample/SearchViewModel.cs
src/Markup/Xamarin.CommunityToolkit.MarkupSample/Xamarin.CommunityToolkit.MarkupSample.csproj

What the title says!
In addition; removed the dependency from the Markup Sample to the NuGet, since that would now always require failing builds and having an additional PR after a new pre-release of XCT was released. Instead it now references the actual Markup source project.
Also in Markup sample fixed a link to point to MicrosoftDocs account

Bump Forms 5 dependency to pre-5

---

src/CommunityToolkit/Xamarin.CommunityToolkit.Sample/Pages/Effects/TouchEffectPage.xaml
src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/Touch/PlatformTouchEffect.android.cs

TouchEffect didn't work with Images (including FFImageLoading). It happened because of FastRenderers structure (They have Container = null)
So we should add ripple native animation directly to the native view's foreground
Use this simple xaml for testing. Enable Native animation and verify ripple appears
```xaml
<Image
Margin="0"
xct:TouchEffect.NativeAnimation="True"
Source="SOME_IMAGE_HERE.png" />
```
- Fixes #660 
None
None

[Android] Make TouchEffect working with Images

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Views/MediaElement/Android/MediaElementRenderer.android.cs

Update volume on media start.
- Fixes #398 
None
None

[Android] MediaElement Volume is only taken into account when set after Media has been started 

---

src/CommunityToolkit/Xamarin.CommunityToolkit.Sample.Android/Properties/AndroidManifest.xml
src/CommunityToolkit/Xamarin.CommunityToolkit.Sample/Pages/Views/MediaElementPage.xaml
src/CommunityToolkit/Xamarin.CommunityToolkit.Sample/Pages/Views/MediaElementPage.xaml.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/MediaElement/Android/MediaElementRenderer.android.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/MediaElement/UWP/MediaElementRenderer.uwp.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/MediaElement/iOS/MediaElementRenderer.ios.cs

We should stop and reset MediaElement if **null** source set.
- Fixes #407 
None
None (only bug fix)

[Bug] null-ing MediaElement.Source has no effect

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Views/MediaElement/Android/MediaElementRenderer.android.cs

Android VideoView opens a separate Window above the current one.
This is because it is based on the SurfaceView.
And we cannot set alpha or perform animations with it because it is not synchronized with your other UI elements.
We may set 0 or 1 alpha only.
- Fixes #530 
None
Android MediaElement is not disappearing if alpha is set to value from the interval (0;1)

Ignore Opacity for Android MediaElement

---

samples/XCT.Sample/Pages/Views/StateLayoutPage.xaml
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/StateLayout/StateLayoutController.shared.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/StateLayout/StateView.shared.cs

Improvements to the `StateLayout` component.
- Fixes #693
Changed:
- `DataTemplate RepeatTemplate` => `DataTemplate Template`
- Changed internal workings deciding when to use `Template` and when to use the `Content` from a `StateView`.

StateLayout enhancements

---

README.md

Fixed: Cannot implictly convert type "int" to "TimeSpan" at line 50
- Fixes #

Fixed: Data type conversion error at line 50

---

samples/XCT.Sample/Pages/TestCases/TestCasesGalleryPage.xaml
samples/XCT.Sample/Pages/TestCases/TouchEffectButtonPage.xaml
samples/XCT.Sample/Pages/TestCases/TouchEffectButtonPage.xaml.cs
samples/XCT.Sample/ViewModels/TestCases/TestCasesGalleryViewModel.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/Touch/GestureManager.shared.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/Touch/PlatformTouchEffect.ios.cs

We call IButtonController.SendClicked method on TouchEffect side because TouchEffet intercepts button's events.
Also, we prevent the iOS button's highlight animation  due to its freezing with TouchEffect (instead we force to enable TouchEffect's native animation)
The **FIRST** test case is added 🥇 
- Fixes #687
None
None

Fix TouchEffect + Button.Command

---

samples/XCT.Sample/Pages/TestCases/MediaElementSourcePage.xaml
samples/XCT.Sample/Pages/TestCases/MediaElementSourcePage.xaml.cs
samples/XCT.Sample/ViewModels/TestCases/TestCasesGalleryViewModel.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Core/MediaSource.shared.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Core/MediaSourceConverter.shared.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/MediaElement/MediaElement.shared.cs

Now the linker will not remove the implicit operators.
- Fixes #688
Changed:
```csharp
[Preserve(Conditional = true)]
public static implicit operator MediaSource(string source);
[Preserve(Conditional = true)]
public static implicit operator MediaSource(Uri uri);
```
Now the users can Binding the MediaElement.Source to a `string`.

Fixed MediaElement.Source

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Views/MediaElement/iOS/MediaElementRenderer.ios.cs

Set Volume on every media source set.
- Fixes #703
None
None

[iOS] MediaElement ignores volume set before media start

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Behaviors/Validators/TextDecorationFlags.shared.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Behaviors/Validators/TextValidationBehavior.shared.cs

Renames `TextValidationBehavior.TextDecorationFlags` `ReduceWhiteSpace` to `NormalizeWhiteSpace` which is a slightly more descriptive name.
NA
Changed:
- `TextDecorationFlags.ReduceWhiteSpace` => `TextDecorationFlags.NormalizeWhiteSpace`
People using this flag will need to update the name, functionality remains exactly the same

Rename reduce to Normalize whitespace for TextValidationBehavior

---

samples/XCT.Sample/Pages/Views/CameraViewPage.xaml
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/CameraView/Android/CameraFragment.android.cs

Fix is based on sample implementations for Camera2 API from Google
- https://github.com/android/camera-samples/blob/4aac9c7763c285d387194a558416a4458f29e275/CameraXTfLite/utils/src/main/java/com/example/android/camera/utils/CameraSizes.kt#L50-L78
- https://github.com/googlearchive/android-Camera2Raw/blob/master/Application/src/main/java/com/example/android/camera2raw/Camera2RawFragment.java#L1069-L1088
- Calculate width and height dependent on orientation
- reduce the reoslution to max. supported preview resolution by Camera2 API (1920x1080)
- Fixes #723
None
None

Fix preview size for camera view on Androud (#723)

---

samples/XCT.Sample/Pages/Behaviors/ImpliedOrderGridBehaviorPage.xaml

Replace the StackLayout by a Grid.

Sample: Fix last button out of the screen

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/Touch/PlatformTouchEffect.android.cs

Prevent TouchEffect crashing on Android when an effect is applied to Image on Android API below 23.
Problem: ```setForeground``` method is available starting API 23.
Solution: just ignore native animation if API is not available.
- Fixes #737
None
None

Fix Android TouchEffect crash

---

samples/XCT.Sample/Xamarin.CommunityToolkit.Sample.csproj
src/CommunityToolkit/Xamarin.CommunityToolkit/Xamarin.CommunityToolkit.csproj
src/Markup/Xamarin.CommunityToolkit.Markup/Xamarin.CommunityToolkit.Markup.csproj

Removes the dependency from the Toolkit to the Markup package. There is no dependency between the packages and currently this installs the Markup package as part of the Toolkit which is not strictly needed.
None for existing installs. People can uninstall the Markup package if they're not using it.

Remove dependency on Markup from Toolkit

---

src/CommunityToolkit/Xamarin.CommunityToolkit.UnitTests/ObjectModel/ICommandTests/AsyncCommandTests/AsyncCommand_Tests.cs
src/CommunityToolkit/Xamarin.CommunityToolkit.UnitTests/ObjectModel/ICommandTests/AsyncValueCommandTests/AsyncValueCommand_Tests.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/ObjectModel/BaseCommand.shared.cs

This PR is base on community feedback from @maxkoshevoi: https://github.com/xamarin/XamarinCommunityToolkit/discussions/709#discussioncomment-270001
Because Xamarin.Forms.Command uses `ChangeCanExecute()`, adding `ChangeCanExecute()` to both `AsyncCommand` and `AsyncValueCommand` enables an easier, more seamless, transition from `Xamarin.Forms.Command` to `Xamarin.CommunityToolkit.ObjectModel.AsyncCommand`.
Adds `BaseCommand.ChangeCanExecute()`
- `BaseCommand.ChangeCanExecute()` leverages `BaseCommand.RaiseCanExecuteChanged()`
None, `BaseCommand.ChangeCanExecute()` leverages `BaseCommand.RaiseCanExecuteChanged()`:
```csharp
public void ChangeCanExecute() => RaiseCanExecuteChanged();
```

Add BaseCommand.ChangeCanExecute()

---

src/CommunityToolkit/Xamarin.CommunityToolkit.UnitTests/Helpers/LocalizationResourceManagerTests/LocalizationResourceManagerTests.cs
src/CommunityToolkit/Xamarin.CommunityToolkit.UnitTests/Mocks/MockResourceManager.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Helpers/LocalizationResourceManager.shared.cs

Turns out `Thread.CurrentThread.CurrentUICulture` is unreliable way to store culture. When new page is created `CurrentUICulture` is reset to default for some reason (even though `ManagedThreadId` is the same).
- Created private field to store culture, so we don't depend on anyone to store it (when resource designer is created by Xamarin it also creates it (see image bellow), so it seems like good approach)
- Also refactored `LocalizationResourceManager` a bit while I have the opportunity
- Added second `Init(ResourceManager resource, CultureInfo initialCulture)` so culture can be set right away. 
- ~~Added setter to `CurrentCulture` and deprecated `SetCulture()`. Culture is handled via properties everywhere (`CultureInfo.CurrentCulture`, `Thread.CurrentThread.CurrentUICulture`, …

Fix culture not persisted to new pages

---

src/CommunityToolkit/Xamarin.CommunityToolkit.UnitTests/Converters/TextCaseConverter_Tests.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Converters/TextCaseConverter.shared.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Converters/TextCaseType.shared.cs

Added support for first char to upper rest to lower case.
Added new enum and logic for that enum to convert a string to first char to upper rest to lower case.
Sample No need for project sample i think:
<Label Text="{Binding Source={x:Static resource:AppResources.Logout}, Converter={StaticResource TextCaseConverter}, ConverterParameter={x:Static converters:TextCaseType.FirstUpperRestLower}}"/>
Regarding  PR check below i really don't know how to fix the rest check boxes. 
- Fixes #
None
Added: 
Added 
FirstUpperRestLower to the TextCaseType enum
Changed:
none
none

Added new TextCaseType to TextCaseConverter

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Views/CameraView/CameraView.shared.cs

Changed PropertyName to fix naming convention.
-Can't test the MACOS compile, but it should work.
-Tests are ok on Windows and working on an Android device
-No samples necessary in my opinion.
-Documentation Update not necessary
- Fixes [#774 ](https://github.com/xamarin/XamarinCommunityToolkit/issues/774)
None
-Intellisense should work now
-MVVM supported with naming convention on CameraView
- [ x] Has tests (MACOS / IOS not tested)
- [x ] Rebased on top of main at time of PR
- [x ] Changes adhere to coding standard

Fixed naming convention of CaptureModeProperty

---

src/CommunityToolkit/Xamarin.CommunityToolkit.UnitTests/ObjectModel/ICommandTests/AsyncCommandTests/AsyncCommand_Tests.cs
src/CommunityToolkit/Xamarin.CommunityToolkit.UnitTests/ObjectModel/ICommandTests/AsyncValueCommandTests/AsyncValueCommand_Tests.cs
src/CommunityToolkit/Xamarin.CommunityToolkit.UnitTests/ObjectModel/ICommandTests/AsyncValueCommandTests/ICommand_AsyncValueCommand_Tests.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/ObjectModel/BaseAsyncCommand.shared.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/ObjectModel/BaseAsyncValueCommand.shared.cs

Tried using new constructors introduced by #782 and got `Null reference exception`.
`canExecute` is mandatory there, but it still can be passed as `null` is some circumstances (see added tests)
None
New AsyncCommand constructors can be called with `canExecute` as `null`

Fix AsyncCommand.CanExecute() null reference exception

---

Directory.Build.props
src/CommunityToolkit/Xamarin.CommunityToolkit/Xamarin.CommunityToolkit.csproj

This change adds some body to the release notes and links people to the right page.
More importantly; this enables the XML documentation generation as a first step for #76. It's clear that we don't have coverage for all public APIs yet (in fact, right now we are about 11k+ short 🙈 ) these XML files, when included in the nuget, should also show IntelliSense which should help people.
- Related to #76
N/A
N/A

Enable XML Docs Generation and Add Release Notes

---

samples/XCT.Sample/ViewModels/Base/BaseGalleryViewModel.cs
samples/XCT.Sample/ViewModels/Behaviors/BehaviorsGalleryViewModel.cs
samples/XCT.Sample/ViewModels/Converters/ConvertersGalleryViewModel.cs
samples/XCT.Sample/ViewModels/Effects/EffectsGalleryViewModel.cs
samples/XCT.Sample/ViewModels/TestCases/TestCasesGalleryViewModel.cs
samples/XCT.Sample/ViewModels/Views/TabViewViewModel.cs
samples/XCT.Sample/ViewModels/Views/ViewsGalleryViewModel.cs
samples/XCT.Sample/ViewModels/WelcomeViewModel.cs

Updates `BaseGalleryViewModel` to always sort `Items` by their `Title`, making the samples galleries easier to navigate.
This only affects `Xamarin.CommunityToolkit.Sample`.
Ensures the Gallery lists are always ordered by their Title.
Here is an example where the `Popup` view appeared at the bottom of the list:
None

Sort BaseGalleryViewModel.Items by Title

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/Touch/PlatformTouchEffect.android.cs

We avoid the double "ripple" effect by setting overlay rippleView **Enabled** property to **False**. We set it to **True** only during manual ripple animation.
For those views which have RippleDrawable as Foreground, we don't start/end ripple animation manually anymore. It's done automatically
- Fixes #804 
None
None
Please try to replicate the bug with the proposed changes.
Also, make sure TouchEffect still works as expected.

[Android] TouchEffect NativeAnimation triggered twice

---

samples/XCT.Sample/Pages/Views/TabView/LazyTabPage.xaml
samples/XCT.Sample/Pages/Views/TabView/LazyTabPage.xaml.cs
samples/XCT.Sample/Pages/Views/TabView/LazyTestView.xaml
samples/XCT.Sample/Pages/Views/TabView/LazyTestView.xaml.cs
samples/XCT.Sample/Pages/Views/TabView/NormalTestView.xaml
samples/XCT.Sample/Pages/Views/TabView/NormalTestView.xaml.cs
samples/XCT.Sample/ViewModels/Views/TabViewViewModel.cs
samples/XCT.Sample/ViewModels/Views/Tabs/LazyTestViewModel.cs
samples/XCT.Sample/ViewModels/Views/Tabs/NormalTestViewModel.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/LazyView/BaseLazyView.shared.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/LazyView/LazyView.shared.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/TabView/TabView.shared.cs

This PR adds a new control called LazyView, with this control we can load any View by demand. The motivation of this control is to make TabView capable to load pages on demand.
Reference: https://www.sharpnado.com/xamarin-forms-lazyview-boost-your-app-reactivity-and-startup-time/
I'll submit the docs soon.
- Fixes #637
Added: 
- `abstract class BaseLazyView`
- `class LazyView<TView> : BaseLazyView where T : View`
None

Implemented LazyView

---

samples/XCT.Sample/Pages/Views/Popups/PopupAnchorPage.xaml

While going through the samples of our shiny new popups, the anchor one crashed at runtime. This because there was a mismatch in casing. Fixed it by changing a whopping 1 character.
NA
NA
Anchor Popup sample now works!
NA

Fixed crash in Popup sample

---

samples/XCT.Sample/Pages/Views/SideMenuViewPage.xaml
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/SideMenuView/SideMenuView.shared.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/SideMenuView/SideMenuViewRenderer.android.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/SideMenuView/SideMenuViewRenderer.ios.cs

Fixed the issue when it was impossible to use Slider with SideMenu because SideMenu intercepted all gestures.
Removed redundant property ```public bool AllowInterceptGesture```.
Moved a couple of methods to the appropriate place in the file.
Refactored default gesture threshold value (it's -1.0 by default now. And each platform determines its own default value)
- Fixes #810
Removed:
property ```bool AllowInterceptGesture``` (it was not helpful and I am pretty sure was not used).
None

[Android] Fix SideMenuView + Slider issue

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Views/LazyView/BaseLazyView.shared.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/LazyView/LazyView.shared.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/TabView/TabView.shared.cs

- Fixes #637
Changed:
- `void LoadView` => `ValueTask LoadViewAsync`

Changed LoadView to be Async

---

samples/XCT.Sample/Pages/Views/Popups/PopupSize.cs

https://github.com/xamarin/XamarinCommunityToolkit/pull/653#issuecomment-757399625
Popup was getting out of screen bound horizontally in Android Sample.
Swap Width and Height values of the Android sample.

Popup out of the screen horizontally in Android sample

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Views/SideMenuView/SideMenuView.shared.cs

Now you can set ```State="LeftMenuShown``` in XAML and the left menu will be shown when you load the view.
- Fixes #822
None
None

SideMenuView: Allow setting State in XAML

---

samples/XCT.Sample/Pages/Views/Popups/ButtonPopup.xaml
samples/XCT.Sample/Pages/Views/Popups/CsharpBindingPopup.xaml
samples/XCT.Sample/Pages/Views/Popups/MultipleButtonPopup.xaml
samples/XCT.Sample/Pages/Views/Popups/NoLightDismissPopup.xaml
samples/XCT.Sample/Pages/Views/Popups/OpenedEventSimplePopup.xaml
samples/XCT.Sample/Pages/Views/Popups/PopupSize.cs
samples/XCT.Sample/Pages/Views/Popups/ReturnResultPopup.xaml
samples/XCT.Sample/Pages/Views/Popups/SimplePopup.xaml
samples/XCT.Sample/Pages/Views/Popups/ToggleSizePopup.xaml
samples/XCT.Sample/Pages/Views/Popups/TransparentPopup.xaml
samples/XCT.Sample/Pages/Views/Popups/XamlBindingPopup.xaml
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/Popup/Android/PopupRenderer.android.cs

[Android] Converting dimensions to pixels in popup renderer

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Behaviors/MaxLengthReachedBehavior.shared.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Behaviors/MaxLengthReachedEventArgs.shared.cs

Added comments/docs for MaxLengthReachedBehavior and MaxLengthReachedEventArgs
- Related #76 
NA
People will be able to enjoy the marvellous inline IntelliSense!

Added inline docs for MaxLengthReachedBehavior

---

samples/XCT.Sample/Pages/Views/SnackBarPage.xaml
samples/XCT.Sample/Pages/Views/SnackBarPage.xaml.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/Snackbar/Helpers/NativeSnackButton.ios.macos.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/Snackbar/Helpers/PaddedLabel.ios.macos.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/Snackbar/Helpers/SnackBarLayout.ios.macos.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/Snackbar/Helpers/SnackBarLayout.uwp.wpf.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/Snackbar/Helpers/iOS/IOSSnackBar.ios.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/Snackbar/Helpers/iOS/SnackBarAppearance.ios.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/Snackbar/Helpers/iOS/SnackbarViews/ActionMessageSnackBarView.ios.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/Snackbar/Helpers/iOS/SnackbarViews/BaseSnackBarView.ios.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/Snackbar/Helpers/iOS/SnackbarViews/MessageSnackBarView.ios.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/Snackbar/Helpers/macOS/MacOSSnackBar.macos.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/Snackbar/Helpers/macOS/SnackBarAppearance.macos.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/Snackbar/Helpers/macOS/SnackbarViews/ActionMessageSnackBarView.macos.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/Snackbar/Helpers/macOS/SnackbarViews/BaseSnackBarView.macos.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/Snackbar/Helpers/macOS/SnackbarViews/MessageSnackBarView.macos.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/Snackbar/Options/MessageOptions.shared.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/Snackbar/Options/SnackBarActionOptions.shared.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/Snackbar/SnackBar.android.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/Snackbar/SnackBar.gtk.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/Snackbar/SnackBar.ios.macos.cs

Add padding for message and action buttons
- Fixes #704
Added: 
- `Thickness Padding { get; set; }`

#704 [Bug] No padding around text in a Toast or Snackbar

---

Directory.Build.props
src/CommunityToolkit/Xamarin.CommunityToolkit/Xamarin.CommunityToolkit.csproj
src/Markup/Xamarin.CommunityToolkit.Markup/Xamarin.CommunityToolkit.Markup.csproj

Fixed our csproj to generate the source link json, and make able to step into our methods during debug sessions. Not sure if we need to add the CI instructions, that you can see [here](https://devblogs.microsoft.com/dotnet/producing-packages-with-source-link/#deterministic-builds).
- Fixes #892
With this change I can see the sourcelink file in the obj folder

fixed csproj to produce sourcelink

---

samples/XCT.Sample/Pages/AboutPage.xaml.cs
samples/XCT.Sample/Pages/Behaviors/ImpliedOrderGridBehaviorPage.xaml.cs
samples/XCT.Sample/Pages/Behaviors/MaxLengthReachedBehaviorPage.xaml.cs
samples/XCT.Sample/Pages/Behaviors/RequiredStringValidationBehaviorPage.xaml.cs
samples/XCT.Sample/Pages/Behaviors/UserStoppedTypingBehaviorPage.xaml.cs
samples/XCT.Sample/Pages/Converters/DateTimeOffsetConverterPage.xaml.cs
samples/XCT.Sample/Pages/Effects/EffectsGalleryPage.xaml.cs
samples/XCT.Sample/Pages/Effects/IconTintColorEffectPage.xaml.cs
samples/XCT.Sample/Pages/Effects/RemoveBorderEffectPage.xaml.cs
samples/XCT.Sample/Pages/Effects/SafeAreaEffectPage.xaml.cs
samples/XCT.Sample/Pages/Effects/SelectAllTextEffectPage.xaml.cs
samples/XCT.Sample/Pages/Effects/TouchEffectPage.xaml.cs

`[XamlCompilation(XamlCompilationOptions.Compile)]` from Sample project code-behind pages, and keep only `[assembly: XamlCompilation(XamlCompilationOptions.Compile)]` in AssemblyInfo.cs
- Fixes #896

[Housekeeping] remove XamlCompilation from code-behind

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Views/TabView/TabView.shared.cs

Changed TabView SelectedIndex property to use TwoWay binding mode
- Fixes #870
Changed:
- `int SelectedIndex` now use TwoWay Binding

Changed TabView SelectedIndex property to use TwoWay binding mode

---

samples/XCT.Sample/Pages/Views/CameraViewPage.xaml.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/CameraView/Android/CameraFragment.android.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/CameraView/MediaCapturedEventArgs.shared.cs

This should fix issue with incorrectly rotated media capture on some Android devices. As [this](https://medium.com/@kenodoggy/solving-image-rotation-on-android-using-camera2-api-7b3ed3518ab6) article implies. The JPEG_ORIENTATION flag in CaptureRequest is effectively ignored in some devices and the Android docs also imply it will have varying effects across devices. 
See [Android docs](https://developer.android.com/reference/android/hardware/camera2/CaptureRequest.html#JPEG_ORIENTATION)
There are two points about the implementation I would like to elaborate on. Firstly the removal or the JPEG_ORIENTATION flag. I wasn't able to reliably determine (in code) across various devices (some with rotation issue some not) if the addition of the flag had rotated the capture data or modified the …

Fix camera media rotation android issue

---

src/CommunityToolkit/Xamarin.CommunityToolkit.UnitTests/ObjectModel/ObservableRangeCollection_Tests.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/ObjectModel/Extensions/INotifyPropertyChangedExtension.shared.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/ObjectModel/Extensions/ObservableRangeCollectionEx.shared.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/ObjectModel/Extensions/ObservableRangeCollectionExtension.shared.cs

Added extension method to `ObservableRangeCollection` so that it can be initialized with another collection in collection initializer.
- Fixes #756
`void Add<T>(this ObservableRangeCollection<T> source, IEnumerable<T> collection)`
`ObservableRangeCollection` now can be initialized with another collection in collection initializer:
```cs
EventTypes = new ListViewModel<EventType>()
{
ItemsSource = { timetableInfo.EventTypes(lessonInfo.Lesson.ID).OrderBy(et => et.Entity.ShortName) }
};
```

Add "Add(IEnumerable<T> collection)" to ObservableRangeCollection<T>

---

src/CommunityToolkit/Xamarin.CommunityToolkit/ObjectModel/Extensions/INotifyPropertyChangedEx.shared.cs

Made WeakSubscribe<T>(this INotifyPropertyChanged target..) EventArgs parameter type more specific (`EventArgs` -> `PropertyChangedEventArgs`).
It was `PropertyChangedEventArgs` from the beginning, but got upcasted by mistake. 
- Fixes #917
Was `WeakSubscribe<T>(this INotifyPropertyChanged target, T subscriber, Action<T, object, EventArgs> action)`
Now `WeakSubscribe<T>(this INotifyPropertyChanged target, T subscriber, Action<T, object, PropertyChangedEventArgs> action)`
Users can now reference `PropertyName` when using `WeakSubscribe`

Make WeakSubscribe<T>(this INotifyPropertyChanged target..) EventArgs parameter type more specific

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Behaviors/Validators/CharactersValidationBehavior.shared.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Behaviors/Validators/EmailValidationBehavior.shared.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Behaviors/Validators/MultiValidationBehavior.shared.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Behaviors/Validators/NumericValidationBehavior.shared.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Behaviors/Validators/RequiredStringValidationBehavior.shared.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Behaviors/Validators/TextValidationBehavior.shared.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Behaviors/Validators/UriValidationBehavior.shared.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Behaviors/Validators/ValidationBehavior.shared.cs

We are eager to allow using ValidationBehavior in async validations. (For example, make a request to the Server Side).
- Fixes #857
Added:
- ```public bool ValidationBehavior.IsRunning { get; set; }```
- ```protected Task<bool> ValidateAsync(object value, CancellationToken token);```
- ```protected object Decorate (object value);```
Removed:
- ```protected bool Validate (object value);```
- ```protected object DecorateValue ();```
None

[Breaking Changes] ValidationBehavior Async checks support

---

src/CommunityToolkit/Xamarin.CommunityToolkit.UnitTests/Converters/ItemSelectedEventArgsConverter_Tests.cs
src/CommunityToolkit/Xamarin.CommunityToolkit.UnitTests/Converters/ItemTappedEventArgsConverter_Tests.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Converters/ItemSelectedEventArgsConverter.shared.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Converters/ItemTappedEventArgsConverter.shared.cs

For example I want to write this in my VM:
```csharp
Coffee selectedCoffee;
public Coffee SelectedCoffee
{
get => selectedCoffee;
set => SetProperty(ref selectedCoffee, value);
}
async Task Selected(Coffee coffee)
{
if (coffee == null)
return;
await Application.Current.MainPage.DisplayAlert("Selected", coffee.Name, "OK");
SelectedCoffee = null;
}
```
And this in my XAML:
```xml
<ListView
SelectedItem="{Binding SelectedCoffee, Mode=TwoWay}"
>
<ListView.Behaviors>
<xct:EventToCommandBehavior
Command="{Binding SelectedCommand}"
EventArgsConverter="{StaticResource ItemSelectedEventArgsConverter}"
EventName="ItemSelected" />
</ListView.Behaviors>
```
Today, this will throw an exception because it it null and is not of the type it is expecting, but that should be allowed.
The only work around …

Don't thrown when tap/selected is null, return null. For deselect.

---

Directory.Build.props
samples/XCT.Sample.Android/Xamarin.CommunityToolkit.Sample.Android.csproj
src/CommunityToolkit/Xamarin.CommunityToolkit/Xamarin.CommunityToolkit.csproj
src/Directory.Build.props

With these changes now we're able to debug Android again and release nugets with source link. Also tested on iOS and is working

Msbuild hotfix

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Extensions/PageExtension.shared.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Extensions/VisualElementExtension.shared.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Helpers/WeakEventManager.shared.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Helpers/WeakEventManagerService.shared.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/TabView/LayoutExtensions.shared.cs

This is more a preference thing, so feel free to reject this PR.
Checking all arguments would be better, but I think at least first one should be checked.
- Fixes #944
None
Extension methods will throw `ArgumentNullException` instead of `NullReferenceException` if first argument is null

Add null checks to first extension method argument

---

src/CommunityToolkit/Xamarin.CommunityToolkit.UnitTests/ObjectModel/Grouping_Tests.cs
src/CommunityToolkit/Xamarin.CommunityToolkit.UnitTests/ObjectModel/ObservableObject_Tests.cs
src/CommunityToolkit/Xamarin.CommunityToolkit.UnitTests/ObjectModel/Person.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/ObjectModel/Grouping.shared.cs

Merge the `Grouping` classes from Refractored.MvvmHelpers (from James Montemagno).
Issue https://github.com/xamarin/XamarinCommunityToolkit/issues/786
Added:
- `class Grouping<TKey, TItem> : ObservableRangeCollection<TItem>`
- `class Grouping<TKey, TSubKey, TItem> : ObservableRangeCollection<TItem>`
No behavioral change, only additions.

Merge `Grouping` classes from Refractored.MvvmHelpers

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Extensions/VisualElementExtension.shared.cs

Add null check
- Fixes #960
None
None (app no longer crashes)

Fix "App crashes on tap of control with NativeAnimation"

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/Touch/PlatformTouchEffect.android.cs

Android Foreground property is available starting API 23. We shouldn't use it on versions lower than it.
- Fixes #969
- Fixes #853
None
None

Fix Java.Lang.NoSuchMethodError in TouchEffect

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Views/MediaElement/iOS/MediaElementRenderer.ios.cs

Adding a defensive null-check to see if we can prevent a NRE with `SeekComplete` for `MediaElement` on iOS
- Fixes #976 
NA
Before would (sometimes) crash on navigating away from the page, now no crash

Add null-check to prevent NRE on MediaElement for iOS

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/Touch/GestureManager.shared.cs

We should cancel previous animations if set value without running new animation. 
- Fixes #974
None
None

View is stuck in pressed state when fast click (if PressedAnimationDuration is set)

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/IconTintColor/IconTintColorEffectRouter.android.cs

Catching `ObjectDisposedException` and ignoring it to avoid a crash.
- Fixes #994

Avoid ImageButtonRenderer ObjectDisposedException on Android

---

samples/XCT.Sample/Pages/Behaviors/CharactersValidationBehaviorPage.xaml
src/CommunityToolkit/Xamarin.CommunityToolkit/Behaviors/Validators/ValidationBehavior.shared.cs

Added support of visual state manger to ValidationBehavior.
- Fixes #952
- Fixes #807

Add VSM to ValidationBehavior

---

samples/XCT.Sample/Pages/Views/SideMenuViewPage.xaml
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/SideMenuView/SideMenuView.shared.cs

Make it possible to scale the main view during the interaction.
- Fixes #1007
Added: 
- `double SideMenuView.MainViewScaleFactor` (attached property)
None

[Enhancement] Add Scale support for SideMenuView

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Views/AvatarView/AvatarView.shared.cs

If the stream is closed, we should try to reopen it rather than crash.
- Fixes #1046 
None
None

Fix AvatarView UriImageSource Stream closed exception

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/RemoveBorder/RemoveBorderEffect.shared.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/RemoveBorder/RemoveBorderEffect.uwp.cs

Implemented RemoveBorderEffect for UWP. 
- Implements #922
n.a.
When attaching the RemoveBorderEffect on Controls like an entry on UWP the border will be gone. On detache border will be restored.

Add remove border effect implementation for uwp

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/Touch/EventArgs/LongPressCompletedEventArgs.shared.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/Touch/GestureManager.shared.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/Touch/TouchEffect.shared.cs

This results in a situation where long presses can only be handled via a Command, and there doesn't seem to be any way of accessing it as an event (which is imperative when implementing controls etc).
- Fixes #851 
Added: 
- `event TouchEffect.LongPressCompleted`
- `class LongPressCompletedEventArgs`
None

[Enhancement] Add LongPressCompleted event to TouchEffect

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Helpers/LocalizedString.shared.cs

Added `Preserve` to `Localized` property
- Fixes #1069
None
None

Fix for LocalizedString not displaying in Release mode

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/IconTintColor/IconTintColorEffectRouter.android.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Extensions/JavaObjectExtensions.android.cs

Replace the Exception approach by the extension used by XF team, more context is found in the linked issue.
- Fixes #1022
Added internal Android extension class `JavaObjectExtensions.android.cs`.

Replace Exception approach by extension used by XF

---

azure-pipelines.yml
src/CommunityToolkit/Xamarin.CommunityToolkit.UnitTests/Helpers/LocalizedStringTests/LocalizedStringTests.cs
src/CommunityToolkit/Xamarin.CommunityToolkit.UnitTests/ObjectModel/ICommandTests/AsyncCommandTests/AsyncCommand_Tests.cs
src/CommunityToolkit/Xamarin.CommunityToolkit.UnitTests/ObjectModel/ICommandTests/AsyncCommandTests/IAsyncCommand_Tests.cs
src/CommunityToolkit/Xamarin.CommunityToolkit.UnitTests/ObjectModel/ICommandTests/AsyncCommandTests/ICommand_AsyncCommand_Tests.cs
src/CommunityToolkit/Xamarin.CommunityToolkit.UnitTests/ObjectModel/ICommandTests/AsyncValueCommandTests/AsyncValueCommand_Tests.cs
src/CommunityToolkit/Xamarin.CommunityToolkit.UnitTests/ObjectModel/ICommandTests/AsyncValueCommandTests/BaseAsyncValueCommandTests.cs
src/CommunityToolkit/Xamarin.CommunityToolkit.UnitTests/ObjectModel/ICommandTests/AsyncValueCommandTests/ICommand_AsyncValueCommand_Tests.cs
src/CommunityToolkit/Xamarin.CommunityToolkit.UnitTests/ObjectModel/ICommandTests/BaseCommandTests.cs
src/CommunityToolkit/Xamarin.CommunityToolkit.UnitTests/Xamarin.CommunityToolkit.UnitTests.csproj
src/CommunityToolkit/Xamarin.CommunityToolkit/ObjectModel/Internals/BaseCommand.gtk.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/ObjectModel/Internals/BaseCommand.netstandard.wpf.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/ObjectModel/Internals/BaseCommand.shared.cs

This PR will resolve the race condition in the `IAsyncCommand` and `IAsyncValueCommand` unit tests that is causing the the tests to timeout.
The timeout happens in [tests like these](https://github.com/xamarin/XamarinCommunityToolkit/blob/b19a3fda461ef691b7a94da87a47088d530383e4/src/CommunityToolkit/Xamarin.CommunityToolkit.UnitTests/ObjectModel/ICommandTests/AsyncCommandTests/AsyncCommand_Tests.cs#L409) where we are verifying that `ICommand.CanExecuteChanged` fires.
An example of the Unit Tests timing out can be seen in this CI build; the Unit Tests on .NET Framework never completed, causing the entire Unit Test suite to timeout after an hour:
https://github.com/xamarin/XamarinCommunityToolkit/pull/1005/checks?check_run_id=2100776335
Right now, this race condition appears to be only …

Resolve `IAsyncCommand` / `IAsyncValueValueCommand` Unit Test Race Condition

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/Touch/GestureManager.shared.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/Touch/TouchEffect.shared.cs

The crash happened when TouchEffect's Command causes the effect's detaching from the Element (Element was null in that case). So when the Completed event tried to get parameters, it led to a crash.
- Fixes #1066 
- Fixes #861
None
None

Fix TouchEffect crash on resetting Application.MainPage

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Views/BadgeView/BadgeView.shared.cs

Added **properyChanged** arg to "BindableProperty.Create" for a BackgroundColor.
- Fixes #1080 
None
None

fix badge background color (#1080)

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/SelectAllText/SelectAllTextEffect.shared.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/SelectAllText/SelectAllTextEffect.uwp.cs

Adds implementation of SelectAllTextEffect for UWP platform. Effect is based on TextBox which is base class of FormsTextBox used for Entry and Edit. 
Sorry no Issue created (yet). 
n.a.
Effect now just works with UWP.

Add UWP implementation for SelectAllTextEffect

---

samples/XCT.Sample/Pages/Views/RangeSliderPage.xaml
src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/Shadow/PlatformShadowEffect.android.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/Shadow/PlatformShadowEffect.ios.macos.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/RangeSlider/RangeSlider.shared.cs

Update RangeSlider appearance (add shadow for iOS and macOS to be more natural look like)
Fixed shadow effect property changed bug
Changed default values of ThumbSize (30 -> 28) and TrackSize (3 -> 4).
Added shadow for thumbs on iOS and macOS

[iOS] Make RangeSlider more natural look like

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Views/AvatarView/AvatarView.shared.cs

Show initials label if images stream is empty
- Fixes #1120
None
None

[AvatarView] Show initials if stream is empty

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Views/StateLayout/StateLayoutController.shared.cs

Initialize `previousState` field with value `LayoutState.None
`
- Fixes #1112

Init previousState field with LayoutState.None

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Views/Expander/Expander.shared.cs

Since updating from XCT 1.0.3 to 1.1.0 the application throws an exception when displaying the main page that contains an Expander.
The crash happens when the property Direction is set to a value other than Down.
We shouldn't crash if Direction is updated before the header is set.
- Fixes #1144
None
None

Fix Expander crash when Direction changed

---

src/CommunityToolkit/Xamarin.CommunityToolkit.UnitTests/Behaviors/AnimationBehavior_Tests.cs
src/CommunityToolkit/Xamarin.CommunityToolkit.UnitTests/Mocks/MockEventView.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Behaviors/Animations/AnimationBehavior.shared.cs

Removed command invocation from AnimationBehavior class because OnTriggerHandled method calls base implementation (base.OnTriggerHandled) that invokes command as well.
https://github.com/xamarin/XamarinCommunityToolkit/blob/main/src/CommunityToolkit/Xamarin.CommunityToolkit/Behaviors/EventToCommandBehavior.shared.cs#L126
- Fixes #1099
None
None

Fix animation behavior fires command twice

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Behaviors/BaseBehavior.shared.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Behaviors/Validators/MultiValidationBehavior.shared.cs

Don't override child's binding context binding in MultiValidationBehavior
- Fixes #1153
None
None

Fix MultiValidationBehavior overwrites external BindingContext bindings

---

azure-pipelines.yml

This Pull Requests Fixes the recurring error in the CI Build Pipeline
```bash
2021-04-05T22:06:43.9268201Z ##[error]src\CommunityToolkit\Xamarin.CommunityToolkit\Xamarin.CommunityToolkit.csproj(0,0): Error : Unable to find package MSBuild.Sdk.Extras. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages
2021-04-05T22:06:43.9281409Z D:\a\1\s\src\CommunityToolkit\Xamarin.CommunityToolkit\Xamarin.CommunityToolkit.csproj : error : Unable to find package MSBuild.Sdk.Extras. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages
2021-04-05T22:06:43.9285676Z ##[error]src\CommunityToolkit\Xamarin.CommunityToolkit\Xamarin.CommunityToolkit.csproj(0,0): Error : C:\Program Files\dotnet\sdk\5.0.201\Sdks\MSBuild.Sdk.Extras\Sdk not found. …
```

Fix CI Build Errors on Build Windows Samples job

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/Shadow/PlatformShadowEffect.uwp.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/Shadow/ShadowEffect.shared.cs

Well, I've implemented this effect via DropShadow (next DS). But DS has strange behavior. DS appears above the element and I decided to pack an element to StackLayout. 
This StackLayout has a structure: 
StackLayout
> Grid (For shadow)
> Element 
After these changes I appended shadow to Grid, and it's working :)
Maybe my solution isn't very good, but I think we have just one way to implement shadow on UWP. 
- Fixes #847
None
None

Implemented shadow on UWP

---

Directory.Build.props
azure-pipelines.yml
samples/XCT.Sample.Android/Properties/AndroidManifest.xml
samples/XCT.Sample.Android/Xamarin.CommunityToolkit.Sample.Android.csproj
samples/XCT.Sample.FSharp/About.txt
samples/XCT.Sample.FSharp/App.fs
samples/XCT.Sample.FSharp/App.xaml
samples/XCT.Sample.FSharp/App.xaml.fs
samples/XCT.Sample.FSharp/AssemblyInfo.fs
samples/XCT.Sample.FSharp/MainPage.xaml
samples/XCT.Sample.FSharp/MainPage.xaml.fs
samples/XCT.Sample.FSharp/Xamarin.CommunityToolkit.Sample.FSharp.fsproj
samples/XCT.Sample.sln

This PR adds `Xamarin.CommunityToolkit.Sample.FSharp.fsproj`.
In an earilier version of Xamarin.CommunityToolkit, it was reported that F# projects couldn't use the Xamarin.CommunityToolkit NuGet package: https://github.com/xamarin/XamarinCommunityToolkit/commit/e569ee3a2f4cabaffdcfad11edbc2ef495cbe51b
This project ensures that all future releases of Xamarin.CommunityToolkit will continue to be compatible with F#.

Add F# Project

---

samples/XCT.Sample/Pages/Views/SideMenuViewPage.xaml
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/SideMenuView/SideMenuAppearanceType.shared.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/SideMenuView/SideMenuView.shared.cs

Enhanced SideMenuView. Allow choosing the desired type of menu appearance. Also, now it's possible to add a "parallax" effect and manage the main view opacity during interaction with menus.
- Fixes #1191
Added: 
- Enum SideMenuAppearanceType (SlideOut, SlideIn, SlideInOut);
- Attached property MainViewOpacityFactorProperty (double, default 1.0);
- Attached property MenuAppearanceTypeProperty (SideMenuAppearanceType, default SideMenuAppearanceType.SlideOut);
- Attached property ParallaxValueProperty (double, default 0.0).
None
Documentation doesn't exist for this view now.

SideMenuView: New types of appearance | Parallax effect | Scale factor

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Views/BaseTemplatedView.shared.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/Expander/Expander.shared.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/SideMenuView/SideMenuView.shared.cs

Do not throw an exception if the "Control" property is accessed (It can be null while control is initializing with updated bindable properties).
Also, I marked cleaned project a little (Get rid of some warnings by avoiding using obsolete API)
- Fixes #1209
None
None

Fix nullable regression RangeSlider crash

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Views/SideMenuView/SideMenuView.shared.cs

MainViewScaleFactor should work in the same way for both Left & Right menus (if menu opened then main view's Scale should be equal scale factor value). Currently, it is wrong for the right menu.
- Fixes #1249 
None
None

[SideMenuView] Fix Right Menu scale factor

---

samples/XCT.Sample.iOS/Info.plist
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/Snackbar/Helpers/iOS/SnackBarAppearance.ios.cs

Fix crash on devices with version lower then ios 13
- Fixes #1252 
The default foreground is white for ios 13 and lower
The default background is gray for ios 13 and lower
Advanced Snackbar
Toast
Anchor Toast

Fix Snackbar/Toast crashes on iOS 12.5.2

---

samples/XCT.Sample/Pages/Effects/ShadowEffectPage.xaml
src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/Shadow/PlatformShadowEffect.android.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/Shadow/PlatformShadowEffect.ios.macos.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/Shadow/PlatformShadowEffect.uwp.cs

Since Android Button is a subclass of Android TextView, we should handle button separately from text view.
Also, we should clear the state list animator and force to set Bounds outline provider for the button.
- Fixes #988
None
None

[ShadowEffect] Fix shadow appearance on Android button

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Views/StateLayout/StateLayout.shared.cs

Updates the BindableProperty for the LayoutController. The DefaultValueCreator will now use pattern matching to validate the bindable object is a Layout<View> if it is not it will throw an InvalidOperationException with a messaging indicating that the given type was not a Layout<View> to make it a bit more clear why things are failing.
- Fixes #1239 
none
Throws more useful error

throw meaningful error on invalid cast

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Views/BaseTemplatedView.shared.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/SideMenuView/SideMenuView.shared.cs

This issue is caused by the failed merge.
Original PR with fix https://github.com/xamarin/XamarinCommunityToolkit/pull/1212/files
- Fixes #1292
None
None

Fixes AvatarView crash on load

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/Touch/PlatformTouchEffect.android.cs

If TouchEffect is applied to View (not layout) that has TapGestureRecognizer, we should manage the ripple state on the TouchEffect renderer side (because TapGestureRecognizer intercepts events)
- Fixes #1304
None
None

[Android] Make working Image + Native TouchEffect + TapGestureRecognizer 

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Views/DrawingView/Service/DrawingViewService.android.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/DrawingView/Service/DrawingViewService.gtk.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/DrawingView/Service/DrawingViewService.ios.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/DrawingView/Service/DrawingViewService.macos.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/DrawingView/Service/DrawingViewService.tizen.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/DrawingView/Service/DrawingViewService.uwp.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/DrawingView/Service/DrawingViewService.wpf.cs

return null in case the image size is too small (the user just put 1 point. we are not able to create a bitmap with this size)

DrawingView return null instead of exception

---

samples/XCT.Sample/Pages/Base/BasePage.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/Snackbar/Helpers/iOS/SnackBarAppearance.ios.cs

Change the default background color for iOS Toast and Snackbar
- Fixes #
Dark theme
Light theme

Change iOS Snackbar/Toast default background color

---

samples/XCT.Sample/Pages/Views/ExpanderPage.xaml
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/Expander/Expander.shared.cs

Add a property that allows setting the view which will be responsible for touch handling (tap over this view will cause expander to expand or collapse).
Also, add base animation length/easing configuration properties.
Documentation updated: https://github.com/MicrosoftDocs/xamarin-communitytoolkit/pull/128
Fixes: #1350
Added: 
- `uint Expander.AnimationLength { get; set; }`
- `Easing Expander.AnimationEasing { get; set; }`
- `View Expander.TouchCaptureView { get; set; }`
None

Expander: Add touch capture view + common animation length / easing properties

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Startup/ToolkitPlatform.android.cs

Cache the Android.Context for use when needed.
- Fixes #1345
Added: 
- `static Context? context;`
Now the app will not crash for missing the Android.Context. If that happens it's because something is really wrong!

Added cache Context value

---

src/CommunityToolkit/Xamarin.CommunityToolkit.UnitTests/Converters/MathExpressionConverter_Tests.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Converters/MathExpressionConverter/MathExpression.shared.cs

Fixes some bugs with MathExpressionConverter 
Fixes bugs: with negative numerics, with functions which takes two arguments (i.e. pow(x, y)), misprint at round func and bug with different cultures.
None
PS. Should I first create a bugs description problem or? If I implemented this converter?

fixed bugs with math expression converter

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Views/Snackbar/Helpers/NativeSnackButton.ios.macos.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/Snackbar/Helpers/iOS/SnackbarViews/BaseSnackBarView.ios.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/Snackbar/Helpers/macOS/SnackbarViews/BaseSnackBarView.macos.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/Snackbar/SnackBar.ios.macos.cs

Set Snackbar anchor on iOS and macOS only if the sender is not Page.
Fix warning `NativeSnackButton called the (UIButtonType) constructor, but this is not allowed.`
- Fixes #1343

Set anchor view only for pages, fix NativeSnackButton

---

samples/XCT.Sample/Pages/TestCases/Popups/PopupModalPage.xaml
samples/XCT.Sample/Pages/TestCases/Popups/PopupModalPage.xaml.cs
samples/XCT.Sample/Pages/TestCases/Popups/SimplePopup.xaml
samples/XCT.Sample/Pages/TestCases/Popups/SimplePopup.xaml.cs
samples/XCT.Sample/ViewModels/TestCases/Popups/PopupModalViewModel.cs
samples/XCT.Sample/ViewModels/TestCases/TestCasesGalleryViewModel.cs
samples/XCT.Sample/Xamarin.CommunityToolkit.Sample.csproj
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/Popup/iOS/PopupRenderer.ios.cs

Actually on iOS, the ViewController is the MainPage ViewController, with this changes if there is any Modal into the MainPage.Navigation.ModalStack, the ViewController is the last modal displayed ViewController.
- Fixes #1189
You can try it with the sample of the issue fixed here : [XF_PopupModalIssue_Fixed.zip](https://github.com/xamarin/XamarinCommunityToolkit/files/6657933/XF_PopupModalIssue_Fixed.zip) 
None
None

Fix iOS - can't show Popup from a modal page

---

samples/XCT.Sample/Pages/Effects/TouchEffectPage.xaml
samples/XCT.Sample/Pages/Effects/TouchEffectPage.xaml.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/Touch/GestureManager.shared.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/Touch/PlatformTouchEffect.ios.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/Touch/TouchEffect.shared.cs

Fixes nested touch effects on iOS
- Fixes #1432
- Also, fixes IsToggled behavior
None
None

Fix Nested Touch Effects

---

samples/XCT.Sample/Pages/Effects/TouchEffectPage.xaml
src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/Touch/PlatformTouchEffect.ios.cs

Starting from 1.2.0 TouchEffect stopped working with Button and ImageButton.
It caused by changes #1435 
Please make sure TouchEffect works fine with Button and ImageButton (Samples added).
Also, make sure Nested TouchEffects work fine so far.
None
None
- [] Has tests (if omitted, state reason in description)

Fixes regression TouchEffect + Button/ImageButton

---

src/CommunityToolkit/Xamarin.CommunityToolkit.UnitTests/Views/DrawingView_Tests.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/DrawingView/DrawingView.shared.cs

This aims to stop all instances sharing the same instance for the `Points` property.
- Fixes #1476
n/a
As per the description, all instances of the `DrawingView` control will now have a unique instance of `Points`.

DrawingView.Points is now unique per instance

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Views/Snackbar/Options/ToastOptions.shared.cs

At some point, this missing use is causing build errors on our CI and all PRs that are in sync with develop branch.

Added missing using System

---

Xamarin.CommunityToolkit.ruleset
src/CommunityToolkit/Xamarin.CommunityToolkit/AssemblyInfo/AssemblyInfo.ios.tvos.watchos.macos.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/Semantic/SemanticEffect.shared.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/Semantic/SemanticEffectRouterBase.android.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/Touch/PlatformTouchEffect.uwp.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Extensions/VisualElement/VisualElementExtensions.uwp.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/CameraView/Android/CameraFragment.android.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/MediaElement/WPF/MediaElementRenderer.wpf.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/Popup/UWP/PopupRenderer.uwp.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/Shield.shared.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/Snackbar/Helpers/NativeRoundedStackView.ios.macos.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Xamarin.CommunityToolkit.csproj

Reduced the number of warnings. Rules changed
- Fixes #1485
SA1000 - space when do use `new`
SA1412 - change files to be UTF-8 files
NU1701 - libs built with another version of .NET Framework
SA1123 - Warning when we use regions

Changed rulesets  to reduce warning noise

---

samples/XCT.Sample.Android/Xamarin.CommunityToolkit.Sample.Android.csproj
samples/XCT.Sample.FSharp/Xamarin.CommunityToolkit.Sample.FSharp.fsproj
samples/XCT.Sample.GTK/Xamarin.CommunityToolkit.Sample.GTK.csproj
samples/XCT.Sample.Tizen/Xamarin.CommunityToolkit.Sample.Tizen.csproj
samples/XCT.Sample.UWP/Xamarin.CommunityToolkit.Sample.UWP.csproj
samples/XCT.Sample.WPF/Xamarin.CommunityToolkit.Sample.WPF.csproj
samples/XCT.Sample.iOS/Xamarin.CommunityToolkit.Sample.iOS.csproj
samples/XCT.Sample/Xamarin.CommunityToolkit.Sample.csproj
src/CommunityToolkit/Xamarin.CommunityToolkit.UnitTests/Xamarin.CommunityToolkit.UnitTests.csproj
src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/Semantic/SemanticEffectRouter.android.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Xamarin.CommunityToolkit.csproj
src/Markup/Xamarin.CommunityToolkit.Markup.UnitTests/Xamarin.CommunityToolkit.Markup.UnitTests.csproj
src/Markup/Xamarin.CommunityToolkit.Markup/Xamarin.CommunityToolkit.Markup.csproj

This Pull Request increases the Xamarin.Forms dependency to v5.0.0.2083.
This is required to accommodate a breaking change introduced in Xamarin.Forms v5.0.0.2083, as noted in the [Release Notes for `Xamarin.CommunityToolkit v1.2.0`](https://github.com/xamarin/XamarinCommunityToolkit/releases/tag/1.2.0):
> The upcoming version of Xamarin.Forms induces a breaking change in Xamarin.CommmunityToolkit by [increasing its `Xamarin.AndroidX.Core` dependency](https://github.com/xamarin/Xamarin.Forms/pull/14101/files#diff-a10b47d2a1fb6f9a0f879b70a6b268191496328089b0bd5776fcbd68759d59dbR25). 
>
> In our next release, v1.3.0, we will increase our Xamarin.Forms dependency to use this new version of Xamarin.Forms and resolve the breaking changes.

Update Xamarin.Forms Dependency to v5.0.0.2083

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/Touch/PlatformTouchEffect.ios.cs

Extend ShouldReceiveTouch to check if touch View is a subview of the renderer
- Fixes #1493
None
None

Fix touch effect for PanCakeView and similar controls

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/Touch/PlatformTouchEffect.android.cs

Attempt to fix ObjectDisposedException that is raised by IsForegroundRippleWithTapGestureRecognizer invocation.
- Fixes #1505
None
None

Fix ObjectDisposedException in Platform Touch Effect on Android

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/Touch/PlatformTouchEffect.ios.cs

We don't need to wait until HandleTouch is finished (like everywhere else in the file) 
- Fixes #1433
None
None

Fix TouchEffect inside ScrollView

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Views/CameraView/iOS/FormsCameraView.ios.cs

Fixed CameraView crashing on FlashMode Torch
The issue is that `photoSettings.FlashMode = (AVCaptureFlashMode)flashMode;` is converting `CameraFlashMode` to `AVCaptureFlashMode` and there is no option for `CameraFlashMode.Torch` in `AVCaptureFlashMode`.
- Fixes #1314

[Bug] Fixed CameraView crash on FlashMode Torch

---

samples/XCT.Sample.Android/MainActivity.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/Semantic/SemanticEffectRouter.android.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/Shadow/PlatformShadowEffect.android.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/StatusBar/BarStyle.android.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/Touch/PlatformTouchEffect.android.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Extensions/Navigation/NavigationExtensions.android.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Extensions/ViewExtensions.android.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Helpers/XCT.android.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Helpers/XCT.ios.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/ObjectModel/Internals/BaseCommand.android.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/AvatarView/ImageSourceValidator.android.ios.macos.uwp.wpf.gtk.tizen.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/RangeSlider/ThumbFrame.shared.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/SideMenuView/SideMenuView.shared.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/ViewSwitcher/TextSwitcherRenderer.android.cs

- Fixes #1552
Added:
Cache to the iOS version avoiding native calls every time.
Changed:
Renamed `ToolkitPlatform.android` to `XCT.android` and migrate it to `Helpers` folder.

Consolidate our XCT platform class

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/Touch/PlatformTouchEffect.ios.cs

CanExecute can be changed during `effect?.HandleTouch(status);` execution. So we need to get the value before that invocation. Also, we always should proceed with native touch handling if the touch is ending (Completed OR Canceled)
- Fixes #1523
None
None

Fix TouchEffect + Command.CanExecute

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Views/CameraView/iOS/FormsCameraView.ios.cs

- Fixes #1442 
Use the same `photoCaptureDelegate` when taking multiple photos.

[Bug] Fixed CameraView Shutter not responding

---

samples/XCT.Sample/Pages/Views/MediaElementPage.xaml
samples/XCT.Sample/Pages/Views/MediaElementPage.xaml.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/MediaElement/Android/MediaElementRenderer.android.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/MediaElement/MediaElement.shared.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/MediaElement/iOS/MediaElementRenderer.ios.cs

See all details in #1415 , just doing this takeover because I didn't want to burden the original author with _another_ rebase.
- Closes #1415 
- Fixes #649 
Added: 
- `double MediaElement.Speed` bindable property
User now has extra property to influence the playback speed

Added Speed Property to mediaelement

---

samples/XCT.Sample/Pages/Views/CameraViewPage.xaml
samples/XCT.Sample/Pages/Views/CameraViewPage.xaml.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/CameraView/iOS/CameraViewRenderer.ios.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/CameraView/iOS/FormsCameraView.ios.cs

Switched setting the flash mode to after the camera is being initialised to make it work when it's set from XAML or anywhere before it is available. Additionally made an exception for the torch when taking a picture as that's not an "official" supported flash mode.
- Fixes #747
NA
Nothing notable except that before it wasn't working or even crashing, now it all works!

 [CameraView] [iOS] Flash does not work fix

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/Touch/GestureManager.shared.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/Touch/PlatformTouchEffect.android.cs

Fix TouchEffect + CollectionView Single Element selection. Also, fix a crash with TouchEffect + PanCakeView + TalkBack
- Fixes #1568
- Fixes #1577
None
None

[Android] Fix TouchEffect issues

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/Touch/PlatformTouchEffect.android.cs

Make ripple invisible for the case described in the bug-ticket
- Fixes #1567
None
None

Fix TouchEffect + CanExecute on Android

---

samples/XCT.Sample/Pages/Converters/MathExpressionConverterPage.xaml
src/CommunityToolkit/Xamarin.CommunityToolkit.UnitTests/Converters/MathExpressionConverter_Tests.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Converters/MathExpressionConverter/MathExpressionConverter.shared.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Converters/MathExpressionConverter/MultiMathExpressionConverter.shared.cs

- Fixes #1608 
Added:
- `public string Expression { get; set; }`

[Enhancement][Converter] Add Expression property to MathExpressionConverter and MultiMathExpressionConverter

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Xamarin.CommunityToolkit.csproj
src/Markup/Xamarin.CommunityToolkit.Markup/Xamarin.CommunityToolkit.Markup.csproj

This Pull Request increases the Xamarin.Forms dependency to v5.0.0.2125.
This new service release of Xamarin.Forms increases the allowed `Xamarin.AndroidX.*` library versions, allowing for greater flexibility for Xamarin Community Toolkit users.  E.g. In the previous version of Xamarin.Forms, the maximum version of  `Xamarin.AndroidX.Core` was `1.4.0`; in this new version of Xamarin.Forms, it is increased to `1.7.0`. (see chart below)
The previous version of Xamarin.Forms (v5.0.0.2083) added upper limits to the  `Xamarin.AndroidX.*` libraries which induced conflicts with other NuGet libraries, [as explained in greater detail here](https://github.com/xamarin/Xamarin.Forms/issues/14417#issuecomment-921149849). 
Because we have [already increased our Xamarin.Forms dependency to …

Increase Xamarin.Forms Dependency to v5.0.0.2125

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Views/DrawingView/Service/DrawingViewService.macos.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/Snackbar/SnackBar.android.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/Snackbar/SnackBar.ios.macos.cs

- Fixes #1678 
snackbar action button on android has correct color

Fix build, Fix snackbar action button color on android, fix ios action button font

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/Semantic/SemanticEffectRouter.uwp.cs

Null views were getting passed into the semantic heading, causing an NRE to get thrown and crashing.
Added a null check to account for this
App will no longer crash if one attempts to set a semantic heading on a null view

Fix NRE for a11y semantic heading

---

.github/ISSUE_TEMPLATE/bug_report_maui_compat_template.md

Adds a specific `maui-compat` issue template to automatically apply a label.

Add specific MauiCompat issue template

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/Touch/TouchEffect.shared.cs

Fix crash on Android when long press command is used for closing modal page
- Fixes #1720

Fix TouchEffect.LongPressCommand causes System.ArgumentNullException when page is popped

---

samples/XCT.Sample/Pages/TestCases/Popups/GH_BUG_1761.xaml
samples/XCT.Sample/Pages/TestCases/Popups/GH_BUG_1761.xaml.cs
samples/XCT.Sample/ViewModels/TestCases/TestCasesGalleryViewModel.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/Popup/PopupOfT.shared.cs

The issue is fully described #1761 
- Fixes #1761 
The fix was tested on the iOS emu+device and Android device, working as expected.

Fix for [iOS] Unable to chain display Popup calls or to display two popup simultaneously #1761

---

MauiCompat.sh
MauiCompatSteps.md
azure-pipelines.yml
src/CommunityToolkit/Xamarin.CommunityToolkit/Core/FileMediaSourceConverter.shared.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/MediaElement/UriTypeConverter.shared.cs

Automate MauiCompat generation, Update MauiCompat to preview 11

Automate MauiCompat build, Update MAUI Preview 11

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Views/CameraView/Android/CameraFragment.android.cs

`CameraView` preview does not work correctly for front facing camera on Xiaomi Note 7/8 devices.
This appears to be a niche issue on Xiaomi devices of a suitable age (the newer ones don't appear to show the issue) where the front camera cannot be used to preview / capture media. Instead of displaying a preview, the media capture failed event is raised & the camera cannot be used.
Below is the XCT sample running on a Xiaomi Redmi Note 7 & a Samsung A21S. The Samsung has no issues displaying the front camera and the Xiaomi cannot display it.
Xiaomi with issue
https://user-images.githubusercontent.com/33064621/147880984-c3600894-d4d6-4bd5-8d15-879f7f8f5ef7.mp4
Samsung without issue
https://user-images.githubusercontent.com/33064621/147881025-d2706bc1-edfa-4cef-9481-b747013192d1.mp4
Upon …

Fixed camera preview for Xiaomi devices

---

samples/XCT.Sample/Pages/TestCases/DrawingViewInExpanderPage.xaml
samples/XCT.Sample/Pages/TestCases/DrawingViewInExpanderPage.xaml.cs
samples/XCT.Sample/ViewModels/TestCases/TestCasesGalleryViewModel.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/DrawingView/Renderer/DrawingViewRenderer.android.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/DrawingView/Renderer/DrawingViewRenderer.gtk.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/DrawingView/Renderer/DrawingViewRenderer.ios.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/DrawingView/Renderer/DrawingViewRenderer.macos.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/DrawingView/Renderer/DrawingViewRenderer.tizen.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/DrawingView/Renderer/DrawingViewRenderer.uwp.cs

Remove null-forgiving operator in drawing view.
I am not able to deploy the app to android device with VS 17.2, I was not able to test it on Android.
It works fine on UWP, WPF
- Fixes #1747

Nullable fixes in DrawingView

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/Shadow/PlatformShadowEffect.ios.macos.cs

The shadow effect is disappearing when coming back to the app.
This issue exists only on iOS and only with the Frame view.
- Fixes #1725
None

[iOS] ShadowEffect disappearing when coming back to the app (only with the Frame view) 

---

MauiCompat.sh

Preview 14

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Views/MediaElement/Android/FormsVideoView.android.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/MediaElement/Android/MediaElementRenderer.android.cs

FormsVideoView instance was never set to null after disposing, which would sometimes lead to accessing the disposed object and throwing ObjectDisposedException.
I have also rearranged method calls in [SetVideoURI](https://github.com/xamarin/XamarinCommunityToolkit/blob/22b1d4ccf45555c2ed89ecb94e9ff93a5cf61ab3/src/CommunityToolkit/Xamarin.CommunityToolkit/Views/MediaElement/Android/FormsVideoView.android.cs#L53) to avoid calling the base method after the await, during which the instance could get disposed because the overridden method is async void. The only downside of this approach I could think of is that the metadata (video size and duration) may update after the video has already started. Maybe we could revert this and override Dispose and set a private field `isDisposed = true` and …

Implemented MediaElement ObjectDisposedException fix

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Views/MediaElement/iOS/MediaElementRenderer.ios.cs

Random crash on iOS with media element and switching sources. I fixed an identical issue with https://github.com/Baseflow/XamarinMediaManager/blob/f72ededd4be0e7c09125e07da2a6627d8b0caeb0/MediaManager/Platforms/Apple/AppleMediaManagerBase.cs
- Fixes https://github.com/xamarin/XamarinCommunityToolkit/issues/746
None

Fix random crash on iOS when switching source

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Views/CameraView/iOS/FormsCameraView.ios.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/MediaElement/iOS/MediaElementRenderer.ios.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/Popup/iOS/PopupRenderer.ios.cs

After chatting with @jadenrogers, I saw that we didn't added all null checks possibles... Not sure why this didn't fail on CI.
- Fixes #1915

Fixed null reference errors

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/Touch/PlatformTouchEffect.android.cs

Added additional ctor `AccessibilityListener(IntPtr handle, JniHandleOwnership transfer)` in order to fix #1923.
- Fixes #1923
None.

added additional ctor to AccessibilityListener to avoid app crash

---

samples/XCT.Sample/Pages/TestCases/Issue1900.xaml
samples/XCT.Sample/Pages/TestCases/Issue1900.xaml.cs
samples/XCT.Sample/ViewModels/TestCases/Issue1900ViewModel.cs
samples/XCT.Sample/ViewModels/TestCases/TestCasesGalleryViewModel.cs
samples/XCT.Sample/Xamarin.CommunityToolkit.Sample.csproj
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/BadgeView/BadgeView.shared.cs

BadgeView default Text value is never set.
The Text property has a default value of 0, but it is never set to the actual label. This prevents the BadgeView from being displayed if it is bound to a property with a value of 0 and AutoHide is set to false.
- Fixes #1900

Fix badge view default text "0"

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Views/CameraView/UWP/CameraViewRenderer.uwp.cs

This fixes the bug from issue #1950 by correctly setting `isPreviewing` so that at clean-up time, the `MediaCapture` object is cleaned up properly.
- Fixes #1950
The `CameraView` on UWP doesn't leak normal and GPU memory anymore.

CameraView: fixed leak on UWP not cleaning up MediaCapture object for preview

---

src/CommunityToolkit/Xamarin.CommunityToolkit/Views/CameraView/UWP/CameraViewRenderer.uwp.cs

This fixes the CameraView on UWP to request microphone permission when CaptureMode is only set to Photo.
- Fixes #1962
The UWP app can then remove the microphone permission if not use anywhere else.

CameraView: only request microphone permission when CaptureMode is set to Video in UWP

---

.github/workflows/backport-trigger.yml

Remove dependency on outdated `backport-bot-action`.  This is part of an overall effort to ensure all repos that support backports are using the latest `backport-action` template
Removes dependency on outdated `backport-bot-action`
Requires the `@gitbot backport` text be specified at the beginning of a PR comment as opposed to appearing anywhere in the comment text

Migrate to backport-action

---

samples/XCT.Sample/Pages/TestCases/Issue1978.xaml
samples/XCT.Sample/Pages/TestCases/Issue1978.xaml.cs
samples/XCT.Sample/ViewModels/TestCases/Issue1978ViewModel.cs
samples/XCT.Sample/ViewModels/TestCases/TestCasesGalleryViewModel.cs
samples/XCT.Sample/Xamarin.CommunityToolkit.Sample.csproj
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/TabView/CupertinoTabViewItemTemplate.shared.cs
src/CommunityToolkit/Xamarin.CommunityToolkit/Views/TabView/WindowsTabViewItemTemplate.shared.cs

TabViewItem font is never set in iOS and UWP, resulting in default font being displayed.
- Fixes #1978 
<details>
<summary><h3>Before</h3></summary>
<table>
<tr><th width='33%'>Android</th><th width='33%'>iOS</th><th width='33%'>UWP</th></tr>
<tr>
<td><img src='https://github.com/xamarin/XamarinCommunityToolkit/assets/25205086/678505db-a884-4b61-890d-0a26bf5b2015' /></td>
<td><img src='https://github.com/xamarin/XamarinCommunityToolkit/assets/25205086/2d949500-73c4-45b6-8b37-dfce81bb3b3d' /></td>
<td><img src='https://github.com/xamarin/XamarinCommunityToolkit/assets/25205086/a1d489c0-1173-4dca-adb2-deb6e759ea31' /></td>
</tr>
</table>
</details>
<details>
<summary><h3>After</h3></summary>
<table>
<tr><th width='33%'>Android</th><th width='33%'>iOS</th><th width='33%'>UWP</th></tr>
<tr> …

Fix tab view item font family (ios and uwp)
